/* ===========================================================
   五班英语角 · 空保执勤英语学习
   data.core.js —— 词汇库（500+ 词，含原有231词 + 新增300+词）
   每条：word / meaning / phonetic / example / exampleCn / category / usage
   usage: 'radio'=无线电通话专用简语  'face'=面对面执勤用语  'write'=书面记录/报告用语  'life'=生活/服务场景通用
=========================================================== */
window.DATA = window.DATA || {};

window.DATA.words = [
/* ---------- 岗位 ---------- */
{ word:'security officer', meaning:'航空安全员', phonetic:'/sɪˈkjʊərəti ˈɒfɪsə(r)/', example:'The security officer is conducting a cabin check.', exampleCn:'航空安全员正在进行客舱检查。', category:'岗位', usage:'write' },
{ word:'crew member', meaning:'机组成员', phonetic:'/kruː ˈmembə(r)/', example:'Please inform the crew member immediately.', exampleCn:'请立即通知机组成员。', category:'岗位', usage:'face' },
{ word:'captain', meaning:'机长', phonetic:'/ˈkæptɪn/', example:'The captain has been informed.', exampleCn:'已通知机长。', category:'岗位', usage:'radio' },
{ word:'flight attendant', meaning:'乘务员', phonetic:'/flaɪt əˈtendənt/', example:'Please contact the flight attendant.', exampleCn:'请联系乘务员。', category:'岗位', usage:'face' },
{ word:'purser', meaning:'乘务长', phonetic:'/ˈpɜːsə(r)/', example:'Report the situation to the purser first.', exampleCn:'先向乘务长报告情况。', category:'岗位', usage:'radio' },
{ word:'first officer', meaning:'副驾驶', phonetic:'/fɜːst ˈɒfɪsə(r)/', example:'The first officer confirmed the cabin is secure.', exampleCn:'副驾驶确认客舱安全。', category:'岗位', usage:'radio' },
{ word:'ground staff', meaning:'地勤人员', phonetic:'/ɡraʊnd stɑːf/', example:'Ground staff will meet the aircraft on arrival.', exampleCn:'地勤人员将在飞机到达时接机。', category:'岗位', usage:'write' },
{ word:'in-flight security coordinator', meaning:'客舱安保协调员', phonetic:'/ɪn flaɪt sɪˈkjʊərəti kəʊˈɔːdɪneɪtə(r)/', example:'The in-flight security coordinator briefed the crew before departure.', exampleCn:'客舱安保协调员在起飞前对机组进行了简报。', category:'岗位', usage:'write' },
/* ---------- 航班 ---------- */
{ word:'international flight', meaning:'国际航班', phonetic:'/ˌɪntəˈnæʃənl flaɪt/', example:'This is an international flight to Dubai.', exampleCn:'这是一趟飞往迪拜的国际航班。', category:'航班', usage:'face' },
{ word:'domestic flight', meaning:'国内航班', phonetic:'/dəˈmestɪk flaɪt/', example:'This is a domestic flight within China.', exampleCn:'这是一趟中国境内的国内航班。', category:'航班', usage:'face' },
{ word:'connecting flight', meaning:'联程航班', phonetic:'/kəˈnektɪŋ flaɪt/', example:'Passengers with a connecting flight should proceed to Gate 12.', exampleCn:'转乘联程航班的旅客请前往12号登机口。', category:'航班', usage:'face' },
{ word:'diverted flight', meaning:'备降航班', phonetic:'/daɪˈvɜːtɪd flaɪt/', example:'The diverted flight landed safely at the alternate airport.', exampleCn:'备降航班安全降落在备降机场。', category:'航班', usage:'write' },
{ word:'flight manifest', meaning:'航班舱单', phonetic:'/flaɪt ˈmænɪfest/', example:'Cross-check the passenger name with the flight manifest.', exampleCn:'将旅客姓名与航班舱单进行核对。', category:'航班', usage:'write' },
/* ---------- 流程 ---------- */
{ word:'boarding', meaning:'登机', phonetic:'/ˈbɔːdɪŋ/', example:'Boarding will begin soon.', exampleCn:'登机即将开始。', category:'流程', usage:'face' },
{ word:'safety briefing', meaning:'安全须知广播', phonetic:'/ˈseɪfti ˈbriːfɪŋ/', example:'Please pay attention to the safety briefing.', exampleCn:'请注意安全须知广播。', category:'流程', usage:'radio' },
{ word:'incident', meaning:'事件', phonetic:'/ˈɪnsɪdənt/', example:'An incident report has been filed.', exampleCn:'已提交事件报告。', category:'流程', usage:'write' },
{ word:'report', meaning:'报告', phonetic:'/rɪˈpɔːt/', example:'Please report the incident immediately.', exampleCn:'请立即报告该事件。', category:'流程', usage:'radio' },
{ word:'security protocol', meaning:'安保流程', phonetic:'/sɪˈkjʊərəti ˈprəʊtəkɒl/', example:'Follow security protocol.', exampleCn:'请遵守安保流程。', category:'流程', usage:'write' },
{ word:'safety check', meaning:'安全检查', phonetic:'/ˈseɪfti tʃek/', example:'Perform a safety check.', exampleCn:'进行安全检查。', category:'流程', usage:'face' },
{ word:'deplane', meaning:'下机', phonetic:'/diːˈpleɪn/', example:'Passengers will deplane after the aircraft stops.', exampleCn:'飞机停稳后旅客将下机。', category:'流程', usage:'face' },
{ word:'landing', meaning:'着陆', phonetic:'/ˈlændɪŋ/', example:'Please prepare for landing.', exampleCn:'请准备着陆。', category:'流程', usage:'radio' },
{ word:'takeoff', meaning:'起飞', phonetic:'/ˈteɪkɒf/', example:'All electronic devices must be secured for takeoff.', exampleCn:'起飞时所有电子设备必须固定好。', category:'流程', usage:'radio' },
{ word:'report incident', meaning:'报告事件', phonetic:'/rɪˈpɔːt ˈɪnsɪdənt/', example:'Report the incident immediately.', exampleCn:'立即报告该事件。', category:'流程', usage:'radio' },
{ word:'incident log', meaning:'事件记录', phonetic:'/ˈɪnsɪdənt lɒɡ/', example:'Write it in the incident log.', exampleCn:'将其记录在事件记录中。', category:'流程', usage:'write' },
{ word:'clear security', meaning:'通过安检', phonetic:'/klɪə sɪˈkjʊərəti/', example:'You have cleared security.', exampleCn:'您已通过安检。', category:'流程', usage:'face' },
{ word:'boarding gate', meaning:'登机口', phonetic:'/ˈbɔːdɪŋ ɡeɪt/', example:'Proceed to the boarding gate.', exampleCn:'请前往登机口。', category:'流程', usage:'face' },
{ word:'final call', meaning:'最后登机广播', phonetic:'/ˈfaɪnl kɔːl/', example:'This is the final call.', exampleCn:'这是最后登机广播。', category:'流程', usage:'radio' },
{ word:'check', meaning:'检查', phonetic:'/tʃek/', example:'Check the area.', exampleCn:'检查该区域。', category:'流程', usage:'face' },
/* ---------- 证件 ---------- */
{ word:'passport', meaning:'护照', phonetic:'/ˈpɑːspɔːt/', example:'Please keep your passport ready.', exampleCn:'请准备好您的护照。', category:'证件', usage:'face' },
{ word:'boarding pass', meaning:'登机牌', phonetic:'/ˈbɔːdɪŋ pɑːs/', example:'Please show me your boarding pass.', exampleCn:'请出示您的登机牌。', category:'证件', usage:'face' },
{ word:'identification', meaning:'身份证明', phonetic:'/aɪˌdentɪfɪˈkeɪʃn/', example:'May I see your identification, please?', exampleCn:'请出示您的身份证明。', category:'证件', usage:'face' },
{ word:'identity verification', meaning:'身份核查', phonetic:'/aɪˈdentəti ˌverɪfɪˈkeɪʃn/', example:'Complete identity verification.', exampleCn:'完成身份核查。', category:'证件', usage:'write' },
{ word:'show your ID', meaning:'出示证件', phonetic:'/ʃəʊ jɔːr aɪˈdiː/', example:'Show your ID please.', exampleCn:'请出示您的证件。', category:'证件', usage:'face' },
{ word:'verify', meaning:'核实', phonetic:'/ˈverɪfaɪ/', example:'Verify the identity.', exampleCn:'核实身份。', category:'证件', usage:'write' },
{ word:'visa', meaning:'签证', phonetic:'/ˈviːzə/', example:'Please make sure your visa is valid.', exampleCn:'请确保您的签证有效。', category:'证件', usage:'face' },
{ word:'crew ID card', meaning:'机组证件', phonetic:'/kruː aɪˈdiː kɑːd/', example:'Please show your crew ID card at the checkpoint.', exampleCn:'请在检查点出示您的机组证件。', category:'证件', usage:'face' },
{ word:'expired document', meaning:'过期证件', phonetic:'/ɪkˈspaɪəd ˈdɒkjumənt/', example:'This is an expired document; it cannot be accepted.', exampleCn:'这是过期证件，不能被接受。', category:'证件', usage:'write' },
{ word:'forged document', meaning:'伪造证件', phonetic:'/fɔːdʒd ˈdɒkjumənt/', example:'We suspect this is a forged document.', exampleCn:'我们怀疑这是一份伪造证件。', category:'证件', usage:'write' },
/* ---------- 行李 ---------- */
{ word:'carry-on baggage', meaning:'随身行李', phonetic:'/ˈkæri ɒn ˈbægɪdʒ/', example:'Please place your carry-on baggage properly.', exampleCn:'请妥善放置随身行李。', category:'行李', usage:'face' },
{ word:'checked baggage', meaning:'托运行李', phonetic:'/tʃekt ˈbægɪdʒ/', example:'Your checked baggage has been loaded.', exampleCn:'您的托运行李已装舱。', category:'行李', usage:'face' },
{ word:'oversized baggage', meaning:'超大行李', phonetic:'/ˌəʊvəˈsaɪzd ˈbægɪdʒ/', example:'This oversized baggage must go into the hold.', exampleCn:'这件超大行李必须放入货舱。', category:'行李', usage:'face' },
{ word:'baggage tag', meaning:'行李牌', phonetic:'/ˈbægɪdʒ tæɡ/', example:'Please keep your baggage tag until arrival.', exampleCn:'请保留您的行李牌直到到达。', category:'行李', usage:'face' },
/* ---------- 客舱 ---------- */
{ word:'overhead bin', meaning:'行李架', phonetic:'/ˈəʊvəhed bɪn/', example:'Please close the overhead bin carefully.', exampleCn:'请小心关闭行李架。', category:'客舱', usage:'face' },
{ word:'aisle', meaning:'过道', phonetic:'/aɪl/', example:'Please keep the aisle clear.', exampleCn:'请保持过道通畅。', category:'客舱', usage:'face' },
{ word:'exit row', meaning:'紧急出口排', phonetic:'/ˈeksɪt rəʊ/', example:'Passengers in the exit row must follow instructions.', exampleCn:'紧急出口排的旅客必须遵守指示。', category:'客舱', usage:'face' },
{ word:'lavatory', meaning:'洗手间', phonetic:'/ˈlævətri/', example:'The lavatory is occupied.', exampleCn:'洗手间有人使用。', category:'客舱', usage:'face' },
{ word:'galley', meaning:'厨房区', phonetic:'/ˈɡæli/', example:'Please do not stay in the galley area.', exampleCn:'请勿在厨房区逗留。', category:'客舱', usage:'face' },
{ word:'jump seat', meaning:'乘务员座椅', phonetic:'/dʒʌmp siːt/', example:'The officer took the jump seat near the door.', exampleCn:'安全员坐在了舱门附近的乘务员座椅上。', category:'客舱', usage:'write' },
{ word:'bulkhead', meaning:'隔舱壁', phonetic:'/ˈbʌlkhed/', example:'The suspect was seated near the bulkhead.', exampleCn:'嫌疑人坐在隔舱壁附近。', category:'客舱', usage:'write' },
{ word:'cabin pressure', meaning:'客舱气压', phonetic:'/ˈkæbɪn ˈpreʃə(r)/', example:'Cabin pressure is being monitored.', exampleCn:'客舱气压正在被监控。', category:'客舱', usage:'radio' },
/* ---------- 安全设备 ---------- */
{ word:'seat belt', meaning:'安全带', phonetic:'/siːt belt/', example:'Please fasten your seat belt.', exampleCn:'请系好安全带。', category:'安全设备', usage:'face' },
{ word:'life vest', meaning:'救生衣', phonetic:'/laɪf vest/', example:'The life vest is under your seat.', exampleCn:'救生衣在您座位下方。', category:'安全设备', usage:'face' },
{ word:'emergency exit', meaning:'紧急出口', phonetic:'/ɪˈmɜːdʒənsi ˈeksɪt/', example:'Please do not block the emergency exit.', exampleCn:'请勿堵塞紧急出口。', category:'安全设备', usage:'face' },
{ word:'oxygen mask', meaning:'氧气面罩', phonetic:'/ˈɒksɪdʒən mɑːsk/', example:'Put on your oxygen mask before helping others.', exampleCn:'请先戴好自己的氧气面罩再帮助他人。', category:'安全设备', usage:'radio' },
{ word:'emergency slide', meaning:'紧急滑梯', phonetic:'/ɪˈmɜːdʒənsi slaɪd/', example:'The emergency slide will deploy automatically.', exampleCn:'紧急滑梯将自动展开。', category:'安全设备', usage:'write' },
{ word:'flare gun', meaning:'信号枪', phonetic:'/fleə(r) ɡʌn/', example:'The flare gun is stored in the security kit.', exampleCn:'信号枪存放在安全装备包中。', category:'安全设备', usage:'write' },
{ word:'restraint kit', meaning:'约束装备', phonetic:'/rɪˈstreɪnt kɪt/', example:'Use the restraint kit only as a last resort.', exampleCn:'约束装备仅作为最后手段使用。', category:'安全设备', usage:'write' },
{ word:'plastic handcuffs', meaning:'塑料手铐', phonetic:'/ˈplæstɪk ˈhændkʌfs/', example:'Apply the plastic handcuffs following procedure.', exampleCn:'按照流程使用塑料手铐。', category:'安全设备', usage:'write' },
/* ---------- 安保 ---------- */
{ word:'restricted area', meaning:'限制区域', phonetic:'/rɪˈstrɪktɪd ˈeəriə/', example:'This is a restricted area.', exampleCn:'这是限制区域。', category:'安保', usage:'face' },
{ word:'security check', meaning:'安全检查', phonetic:'/sɪˈkjʊərəti tʃek/', example:'We are conducting a routine security check.', exampleCn:'我们正在进行例行安全检查。', category:'安保', usage:'face' },
{ word:'cabin check', meaning:'客舱检查', phonetic:'/ˈkæbɪn tʃek/', example:'Please complete the cabin check before departure.', exampleCn:'请在起飞前完成客舱检查。', category:'安保', usage:'write' },
{ word:'screening', meaning:'安检 / 筛查', phonetic:'/ˈskriːnɪŋ/', example:'All passengers must pass security screening.', exampleCn:'所有旅客必须通过安检。', category:'安保', usage:'face' },
{ word:'inspection', meaning:'检查', phonetic:'/ɪnˈspekʃn/', example:'Your bag requires further inspection.', exampleCn:'您的行李需要进一步检查。', category:'安保', usage:'face' },
{ word:'suspicious item', meaning:'可疑物品', phonetic:'/səˈspɪʃəs ˈaɪtəm/', example:'A suspicious item was found near the seat.', exampleCn:'座位附近发现了可疑物品。', category:'安保', usage:'radio' },
{ word:'prohibited item', meaning:'违禁物品', phonetic:'/prəˈhɪbɪtɪd ˈaɪtəm/', example:'This is a prohibited item.', exampleCn:'这是违禁物品。', category:'安保', usage:'face' },
{ word:'dangerous goods', meaning:'危险品', phonetic:'/ˈdeɪndʒərəs ɡʊdz/', example:'Dangerous goods must be declared.', exampleCn:'危险品必须申报。', category:'安保', usage:'face' },
{ word:'unattended baggage', meaning:'无人看管行李', phonetic:'/ˌʌnəˈtendɪd ˈbægɪdʒ/', example:'Please report unattended baggage immediately.', exampleCn:'请立即报告无人看管行李。', category:'安保', usage:'radio' },
{ word:'body search', meaning:'人身检查', phonetic:'/ˈbɒdi sɜːtʃ/', example:'A body search may be required.', exampleCn:'可能需要进行人身检查。', category:'安保', usage:'write' },
{ word:'pat-down search', meaning:'人工搜身检查', phonetic:'/ˈpæt daʊn sɜːtʃ/', example:'A pat-down search will be conducted.', exampleCn:'将进行人工搜身检查。', category:'安保', usage:'face' },
{ word:'security threat', meaning:'安全威胁', phonetic:'/sɪˈkjʊərəti θret/', example:'We are dealing with a possible security threat.', exampleCn:'我们正在处理一个可能的安全威胁。', category:'安保', usage:'radio' },
{ word:'access control', meaning:'出入控制', phonetic:'/ˈækses kənˈtrəʊl/', example:'Access control is required.', exampleCn:'需要实行出入控制。', category:'安保', usage:'write' },
{ word:'restricted access', meaning:'限制进入', phonetic:'/rɪˈstrɪktɪd ˈækses/', example:'This area has restricted access.', exampleCn:'此区域限制进入。', category:'安保', usage:'face' },
{ word:'security clearance', meaning:'安全许可', phonetic:'/sɪˈkjʊərəti ˈklɪərəns/', example:'You need security clearance.', exampleCn:'您需要安全许可。', category:'安保', usage:'write' },
{ word:'unauthorized access', meaning:'未经授权进入', phonetic:'/ʌnˈɔːθəraɪzd ˈækses/', example:'Unauthorized access detected.', exampleCn:'检测到未经授权的进入。', category:'安保', usage:'radio' },
{ word:'threat detection', meaning:'威胁识别', phonetic:'/θret dɪˈtekʃn/', example:'Threat detection is critical.', exampleCn:'威胁识别至关重要。', category:'安保', usage:'write' },
{ word:'restrict', meaning:'限制', phonetic:'/rɪˈstrɪkt/', example:'Access is restricted.', exampleCn:'进入受到限制。', category:'安保', usage:'face' },
{ word:'identify', meaning:'识别', phonetic:'/aɪˈdentɪfaɪ/', example:'Identify the suspect.', exampleCn:'识别嫌疑人。', category:'安保', usage:'write' },
/* ---------- 旅客处置 ---------- */
{ word:'warning', meaning:'警告', phonetic:'/ˈwɔːnɪŋ/', example:'This is an official warning.', exampleCn:'这是一次正式警告。', category:'旅客处置', usage:'face' },
{ word:'non-compliance', meaning:'不配合', phonetic:'/ˌnɒn kəmˈplaɪəns/', example:'Repeated non-compliance may lead to further action.', exampleCn:'反复不配合可能导致进一步措施。', category:'旅客处置', usage:'write' },
{ word:'disruptive passenger', meaning:'扰乱秩序旅客', phonetic:'/dɪsˈrʌptɪv ˈpæsɪndʒə(r)/', example:'The disruptive passenger must remain seated.', exampleCn:'扰乱秩序的旅客必须保持就座。', category:'旅客处置', usage:'write' },
{ word:'aggressive behavior', meaning:'攻击性行为', phonetic:'/əˈɡresɪv bɪˈheɪvjə(r)/', example:'Aggressive behavior will not be tolerated.', exampleCn:'攻击性行为是不被容忍的。', category:'旅客处置', usage:'write' },
{ word:'intoxicated passenger', meaning:'醉酒旅客', phonetic:'/ɪnˈtɒksɪkeɪtɪd ˈpæsɪndʒə(r)/', example:'The intoxicated passenger needs monitoring.', exampleCn:'醉酒旅客需要监控。', category:'旅客处置', usage:'write' },
{ word:'escort', meaning:'护送 / 带离', phonetic:'/ˈeskɔːt/', example:'The passenger will be escorted off the aircraft.', exampleCn:'该旅客将被护送下机。', category:'旅客处置', usage:'face' },
{ word:'restraint', meaning:'约束 / 控制', phonetic:'/rɪˈstreɪnt/', example:'Restraint should be used only when necessary.', exampleCn:'约束措施仅在必要时使用。', category:'旅客处置', usage:'write' },
{ word:'unruly passenger', meaning:'不守规矩旅客', phonetic:'/ʌnˈruːli ˈpæsɪndʒə/', example:'The unruly passenger must be handled.', exampleCn:'不守规矩的旅客必须被处理。', category:'旅客处置', usage:'write' },
{ word:'verbal abuse', meaning:'言语攻击', phonetic:'/ˈvɜːbl əˈbjuːs/', example:'Verbal abuse is not allowed.', exampleCn:'不允许言语攻击。', category:'旅客处置', usage:'write' },
{ word:'physical confrontation', meaning:'肢体冲突', phonetic:'/ˈfɪzɪkl ˌkɒnfrənˈteɪʃn/', example:'Avoid physical confrontation.', exampleCn:'避免肢体冲突。', category:'旅客处置', usage:'write' },
{ word:'control passenger', meaning:'控制旅客', phonetic:'/kənˈtrəʊl ˈpæsɪndʒə/', example:'We need to control the passenger.', exampleCn:'我们需要控制该旅客。', category:'旅客处置', usage:'radio' },
{ word:'escort off', meaning:'带离下机', phonetic:'/ˈeskɔːt ɒf/', example:'He will be escorted off.', exampleCn:'他将被带离下机。', category:'旅客处置', usage:'face' },
{ word:'passenger dispute', meaning:'旅客纠纷', phonetic:'/ˈpæsɪndʒə dɪˈspjuːt/', example:'A passenger dispute occurred.', exampleCn:'发生了旅客纠纷。', category:'旅客处置', usage:'write' },
{ word:'seat conflict', meaning:'座位冲突', phonetic:'/siːt ˈkɒnflɪkt/', example:'There is a seat conflict.', exampleCn:'发生了座位冲突。', category:'旅客处置', usage:'write' },
{ word:'refuse to comply', meaning:'拒绝配合', phonetic:'/rɪˈfjuːz tə kəmˈplaɪ/', example:'The passenger refused to comply.', exampleCn:'该旅客拒绝配合。', category:'旅客处置', usage:'write' },
/* ---------- 沟通 ---------- */
{ word:'cooperate', meaning:'配合', phonetic:'/kəʊˈɒpəreɪt/', example:'Please cooperate with the crew.', exampleCn:'请配合机组人员。', category:'沟通', usage:'face' },
{ word:'remain seated', meaning:'保持就座', phonetic:'/rɪˈmeɪn ˈsiːtɪd/', example:'Please remain seated until further notice.', exampleCn:'在进一步通知前请保持就座。', category:'沟通', usage:'face' },
{ word:'calm down', meaning:'冷静下来', phonetic:'/kɑːm daʊn/', example:'Sir, please calm down.', exampleCn:'先生，请冷静下来。', category:'沟通', usage:'face' },
{ word:'follow instructions', meaning:'听从指示', phonetic:'/ˈfɒləʊ ɪnˈstrʌkʃnz/', example:"Please follow the crew's instructions.", exampleCn:'请听从机组人员的指示。', category:'沟通', usage:'face' },
{ word:'keep distance', meaning:'保持距离', phonetic:'/kiːp ˈdɪstəns/', example:'Please keep distance from the restricted area.', exampleCn:'请与限制区域保持距离。', category:'沟通', usage:'face' },
{ word:'keep calm', meaning:'保持冷静', phonetic:'/kiːp kɑːm/', example:'Please keep calm.', exampleCn:'请保持冷静。', category:'沟通', usage:'face' },
{ word:'guide', meaning:'引导', phonetic:'/ɡaɪd/', example:'Guide the passenger.', exampleCn:'引导旅客。', category:'沟通', usage:'face' },
{ word:'direct', meaning:'指引', phonetic:'/dəˈrekt/', example:'Direct passengers.', exampleCn:'指引旅客。', category:'沟通', usage:'face' },
/* ---------- 执勤 ---------- */
{ word:'security patrol', meaning:'安全巡查', phonetic:'/sɪˈkjʊərəti pəˈtrəʊl/', example:'The security patrol is ongoing.', exampleCn:'安全巡查正在进行中。', category:'执勤', usage:'write' },
{ word:'cabin surveillance', meaning:'客舱监控', phonetic:'/ˈkæbɪn səˈveɪləns/', example:'Maintain cabin surveillance at all times.', exampleCn:'始终保持客舱监控。', category:'执勤', usage:'write' },
{ word:'risk assessment', meaning:'风险评估', phonetic:'/rɪsk əˈsesmənt/', example:'Conduct a risk assessment.', exampleCn:'进行风险评估。', category:'执勤', usage:'write' },
{ word:'behavior monitoring', meaning:'行为监控', phonetic:'/bɪˈheɪvjə ˈmɒnɪtərɪŋ/', example:'Behavior monitoring is required.', exampleCn:'需要进行行为监控。', category:'执勤', usage:'write' },
{ word:'compliance check', meaning:'合规检查', phonetic:'/kəmˈplaɪəns tʃek/', example:'Perform a compliance check.', exampleCn:'进行合规检查。', category:'执勤', usage:'write' },
{ word:'risk control', meaning:'风险控制', phonetic:'/rɪsk kənˈtrəʊl/', example:'Implement risk control measures.', exampleCn:'实施风险控制措施。', category:'执勤', usage:'write' },
{ word:'routine patrol', meaning:'例行巡查', phonetic:'/ruːˈtiːn pəˈtrəʊl/', example:'Routine patrol is ongoing.', exampleCn:'例行巡查正在进行中。', category:'执勤', usage:'write' },
{ word:'passenger control', meaning:'旅客管控', phonetic:'/ˈpæsɪndʒə kənˈtrəʊl/', example:'Maintain passenger control.', exampleCn:'维持旅客管控。', category:'执勤', usage:'radio' },
{ word:'maintain order', meaning:'维持秩序', phonetic:'/meɪnˈteɪn ˈɔːdə/', example:'Maintain order in the cabin.', exampleCn:'在客舱内维持秩序。', category:'执勤', usage:'face' },
{ word:'monitor', meaning:'监控', phonetic:'/ˈmɒnɪtə/', example:'Monitor the cabin situation.', exampleCn:'监控客舱情况。', category:'执勤', usage:'radio' },
{ word:'observe', meaning:'观察', phonetic:'/əbˈzɜːv/', example:'Observe passenger behavior.', exampleCn:'观察旅客行为。', category:'执勤', usage:'write' },
/* ---------- 处置 ---------- */
{ word:'control situation', meaning:'控制局面', phonetic:'/kənˈtrəʊl ˌsɪtʃuˈeɪʃn/', example:'We need to control the situation.', exampleCn:'我们需要控制局面。', category:'处置', usage:'radio' },
{ word:'incident response', meaning:'事件处置', phonetic:'/ˈɪnsɪdənt rɪˈspɒns/', example:'Initiate incident response.', exampleCn:'启动事件处置。', category:'处置', usage:'write' },
{ word:'verbal warning', meaning:'口头警告', phonetic:'/ˈvɜːbl ˈwɔːnɪŋ/', example:'The passenger received a verbal warning.', exampleCn:'该旅客收到了口头警告。', category:'处置', usage:'write' },
{ word:'final warning', meaning:'最后警告', phonetic:'/ˈfaɪnl ˈwɔːnɪŋ/', example:'This is your final warning.', exampleCn:'这是您的最后警告。', category:'处置', usage:'face' },
{ word:'control', meaning:'控制', phonetic:'/kənˈtrəʊl/', example:'Control the situation.', exampleCn:'控制局面。', category:'处置', usage:'radio' },
{ word:'handle', meaning:'处理', phonetic:'/ˈhændl/', example:'Handle the situation.', exampleCn:'处理该情况。', category:'处置', usage:'radio' },
{ word:'warn', meaning:'警告', phonetic:'/wɔːn/', example:'Warn the passenger.', exampleCn:'警告该旅客。', category:'处置', usage:'face' },
{ word:'secure', meaning:'确保安全 / 控制', phonetic:'/sɪˈkjʊə/', example:'Secure the area.', exampleCn:'确保该区域安全。', category:'处置', usage:'radio' },
/* ---------- 指令 ---------- */
{ word:'command order', meaning:'指令命令', phonetic:'/kəˈmɑːnd ˈɔːdə/', example:'Follow the command order.', exampleCn:'服从指令命令。', category:'指令', usage:'radio' },
{ word:'follow order', meaning:'服从命令', phonetic:'/ˈfɒləʊ ˈɔːdə/', example:'Please follow the order.', exampleCn:'请服从命令。', category:'指令', usage:'face' },
{ word:'step back', meaning:'后退', phonetic:'/step bæk/', example:'Please step back.', exampleCn:'请后退。', category:'指令', usage:'face' },
{ word:'stay seated', meaning:'保持坐好', phonetic:'/steɪ ˈsiːtɪd/', example:'Stay seated at all times.', exampleCn:'始终保持坐好。', category:'指令', usage:'face' },
{ word:'hands visible', meaning:'双手可见', phonetic:'/hændz ˈvɪzəbl/', example:'Keep your hands visible.', exampleCn:'保持双手可见。', category:'指令', usage:'face' },
{ word:'do not move', meaning:'不要移动', phonetic:'/duː nɒt muːv/', example:'Do not move.', exampleCn:'不要移动。', category:'指令', usage:'face' },
{ word:'wait here', meaning:'在此等候', phonetic:'/weɪt hɪə/', example:'Please wait here.', exampleCn:'请在此等候。', category:'指令', usage:'face' },
{ word:'move aside', meaning:'让开', phonetic:'/muːv əˈsaɪd/', example:'Please move aside.', exampleCn:'请让开。', category:'指令', usage:'face' },
{ word:'put your hands up', meaning:'举起双手', phonetic:'/pʊt jɔː hændz ʌp/', example:'Put your hands up slowly.', exampleCn:'请慢慢举起双手。', category:'指令', usage:'face' },
{ word:'get down', meaning:'趴下', phonetic:'/ɡet daʊn/', example:'Get down now!', exampleCn:'现在马上趴下！', category:'指令', usage:'face' },
{ word:'freeze', meaning:'不许动', phonetic:'/friːz/', example:'Freeze! Do not move!', exampleCn:'不许动！', category:'指令', usage:'face' },
{ word:'drop it', meaning:'放下（物品）', phonetic:'/drɒp ɪt/', example:'Drop it and step back.', exampleCn:'放下并后退。', category:'指令', usage:'face' },
/* ---------- 安检 ---------- */
{ word:'manual inspection', meaning:'人工检查', phonetic:'/ˈmænjuəl ɪnˈspekʃn/', example:'Conduct a manual inspection.', exampleCn:'进行人工检查。', category:'安检', usage:'write' },
{ word:'secondary screening', meaning:'二次安检', phonetic:'/ˈsekəndəri ˈskriːnɪŋ/', example:'Passenger selected for secondary screening.', exampleCn:'该旅客被选中进行二次安检。', category:'安检', usage:'write' },
{ word:'passenger screening', meaning:'旅客筛查', phonetic:'/ˈpæsɪndʒə ˈskriːnɪŋ/', example:'Passenger screening is required.', exampleCn:'需要进行旅客筛查。', category:'安检', usage:'write' },
{ word:'open your bag', meaning:'打开行李', phonetic:'/ˈəʊpən jɔː bæg/', example:'Please open your bag.', exampleCn:'请打开您的行李。', category:'安检', usage:'face' },
{ word:'remove item', meaning:'取出物品', phonetic:'/rɪˈmuːv ˈaɪtəm/', example:'Remove the item from your bag.', exampleCn:'从行李中取出该物品。', category:'安检', usage:'face' },
{ word:'empty pockets', meaning:'清空口袋', phonetic:'/ˈempti ˈpɒkɪts/', example:'Please empty your pockets.', exampleCn:'请清空您的口袋。', category:'安检', usage:'face' },
{ word:'scan baggage', meaning:'扫描行李', phonetic:'/skæn ˈbægɪdʒ/', example:'Scan the baggage again.', exampleCn:'再次扫描行李。', category:'安检', usage:'write' },
{ word:'inspect', meaning:'检查', phonetic:'/ɪnˈspekt/', example:'Inspect the luggage carefully.', exampleCn:'仔细检查行李。', category:'安检', usage:'face' },
{ word:'scan', meaning:'扫描', phonetic:'/skæn/', example:'Scan the baggage.', exampleCn:'扫描行李。', category:'安检', usage:'face' },
{ word:'detect', meaning:'检测', phonetic:'/dɪˈtekt/', example:'Detect prohibited items.', exampleCn:'检测违禁物品。', category:'安检', usage:'write' },
{ word:'search', meaning:'搜查', phonetic:'/sɜːtʃ/', example:'Search the bag.', exampleCn:'搜查该行李。', category:'安检', usage:'face' },
{ word:'X-ray machine', meaning:'X光安检机', phonetic:'/ˈeks reɪ məˈʃiːn/', example:'Put your bag through the X-ray machine.', exampleCn:'请将行李放入X光安检机。', category:'安检', usage:'face' },
{ word:'explosive trace detector', meaning:'痕量爆炸物探测仪', phonetic:'/ɪkˈspləʊsɪv treɪs dɪˈtektə(r)/', example:'The bag was swabbed by the explosive trace detector.', exampleCn:'该行李已用痕量爆炸物探测仪进行了擦拭检测。', category:'安检', usage:'write' },
{ word:'liquid restriction', meaning:'液体限制规定', phonetic:'/ˈlɪkwɪd rɪˈstrɪkʃn/', example:'Liquids over 100ml are subject to liquid restriction.', exampleCn:'超过100毫升的液体受液体限制规定约束。', category:'安检', usage:'face' },
{ word:'random check', meaning:'随机抽检', phonetic:'/ˈrændəm tʃek/', example:'You have been selected for a random check.', exampleCn:'您被选中进行随机抽检。', category:'安检', usage:'face' },
/* ---------- 设备 ---------- */
{ word:'surveillance camera', meaning:'监控摄像头', phonetic:'/səˈveɪləns ˈkæmərə/', example:'Check the surveillance camera.', exampleCn:'查看监控摄像头。', category:'设备', usage:'write' },
{ word:'metal detector', meaning:'金属探测器', phonetic:'/ˈmetl dɪˈtektə/', example:'Walk through the metal detector.', exampleCn:'请通过金属探测器。', category:'设备', usage:'face' },
{ word:'handheld detector', meaning:'手持探测器', phonetic:'/ˈhændheld dɪˈtektə(r)/', example:'The officer used a handheld detector for the pat-down.', exampleCn:'安全员使用手持探测器进行搜身检查。', category:'设备', usage:'write' },
{ word:'baton', meaning:'警棍', phonetic:'/ˈbætən/', example:'The baton is carried as standard equipment.', exampleCn:'警棍作为标准装备随身携带。', category:'设备', usage:'write' },
{ word:'walkie-talkie', meaning:'对讲机', phonetic:'/ˌwɔːki ˈtɔːki/', example:'Use the walkie-talkie to contact the cockpit.', exampleCn:'使用对讲机联系驾驶舱。', category:'设备', usage:'face' },
/* ---------- 执法 ---------- */
{ word:'law enforcement', meaning:'执法人员', phonetic:'/lɔː ɪnˈfɔːsmənt/', example:'Law enforcement has been notified.', exampleCn:'已通知执法人员。', category:'执法', usage:'radio' },
{ word:'detain', meaning:'扣留', phonetic:'/dɪˈteɪn/', example:'The passenger was detained.', exampleCn:'该旅客被扣留。', category:'执法', usage:'write' },
{ word:'arrest', meaning:'逮捕', phonetic:'/əˈrest/', example:'The suspect was placed under arrest on arrival.', exampleCn:'嫌疑人在到达后被逮捕。', category:'执法', usage:'write' },
{ word:'take into custody', meaning:'羁押 / 拘留', phonetic:'/teɪk ˈɪntə ˈkʌstədi/', example:'He was taken into custody by airport police.', exampleCn:'他被机场警方羁押。', category:'执法', usage:'write' },
{ word:'hand over to police', meaning:'移交警方', phonetic:'/hænd ˈəʊvə tə pəˈliːs/', example:'We will hand the passenger over to police on landing.', exampleCn:'落地后我们将把该旅客移交警方。', category:'执法', usage:'radio' },
/* ---------- 安全 ---------- */
{ word:'threat level', meaning:'威胁等级', phonetic:'/θret ˈlevl/', example:'The threat level has increased.', exampleCn:'威胁等级已提高。', category:'安全', usage:'write' },
{ word:'secure area', meaning:'安全区域', phonetic:'/sɪˈkjʊə ˈeəriə/', example:'Move to a secure area.', exampleCn:'前往安全区域。', category:'安全', usage:'face' },
{ word:'security alert', meaning:'安全警报', phonetic:'/sɪˈkjʊərəti əˈlɜːt/', example:'A security alert has been issued.', exampleCn:'已发布安全警报。', category:'安全', usage:'radio' },
{ word:'safety compliance', meaning:'安全遵守', phonetic:'/ˈseɪfti kəmˈplaɪəns/', example:'Ensure safety compliance.', exampleCn:'确保安全遵守。', category:'安全', usage:'write' },
{ word:'prevent', meaning:'防止', phonetic:'/prɪˈvent/', example:'Prevent any incident.', exampleCn:'防止任何事件发生。', category:'安全', usage:'write' },
/* ---------- 应急 ---------- */
{ word:'emergency landing', meaning:'紧急降落', phonetic:'/ɪˈmɜːdʒənsi ˈlændɪŋ/', example:'Prepare for emergency landing.', exampleCn:'准备紧急降落。', category:'应急', usage:'radio' },
{ word:'forced landing', meaning:'迫降', phonetic:'/fɔːst ˈlændɪŋ/', example:'The aircraft made a forced landing.', exampleCn:'飞机进行了迫降。', category:'应急', usage:'write' },
{ word:'respond', meaning:'应对', phonetic:'/rɪˈspɒnd/', example:'Respond quickly.', exampleCn:'迅速应对。', category:'应急', usage:'radio' },
{ word:'evacuation', meaning:'紧急撤离', phonetic:'/ɪˌvækjuˈeɪʃn/', example:'Prepare the cabin for evacuation.', exampleCn:'为紧急撤离准备客舱。', category:'应急', usage:'radio' },
{ word:'brace position', meaning:'防冲击姿势', phonetic:'/breɪs pəˈzɪʃn/', example:'Assume the brace position immediately.', exampleCn:'立即采取防冲击姿势。', category:'应急', usage:'radio' },
{ word:'ditching', meaning:'水上迫降', phonetic:'/ˈdɪtʃɪŋ/', example:'The crew is trained for ditching procedures.', exampleCn:'机组已接受水上迫降程序培训。', category:'应急', usage:'write' },
{ word:'decompression', meaning:'座舱释压', phonetic:'/ˌdiːkəmˈpreʃn/', example:'Rapid decompression triggered the oxygen masks.', exampleCn:'座舱快速释压触发了氧气面罩。', category:'应急', usage:'radio' },
{ word:'smoke in cabin', meaning:'客舱冒烟', phonetic:'/sməʊk ɪn ˈkæbɪn/', example:'Report any smoke in cabin immediately.', exampleCn:'如发现客舱冒烟请立即报告。', category:'应急', usage:'radio' },
{ word:'fire onboard', meaning:'机上火情', phonetic:'/ˈfaɪər ɒnˈbɔːd/', example:'A fire onboard requires immediate action.', exampleCn:'机上火情需要立即处置。', category:'应急', usage:'radio' },
{ word:'emergency landing gear', meaning:'应急起落架', phonetic:'/ɪˈmɜːdʒənsi ˈlændɪŋ ɡɪə(r)/', example:'The emergency landing gear was deployed manually.', exampleCn:'应急起落架已手动放出。', category:'应急', usage:'write' },
/* ---------- 反劫机处置 ---------- */
{ word:'hijack', meaning:'劫持（飞机）', phonetic:'/ˈhaɪdʒæk/', example:'The crew was trained to respond to a hijack attempt.', exampleCn:'机组接受过应对劫机企图的训练。', category:'反劫机处置', usage:'write' },
{ word:'hijacker', meaning:'劫机者', phonetic:'/ˈhaɪdʒækə(r)/', example:'The hijacker demanded to speak with the pilot.', exampleCn:'劫机者要求与飞行员对话。', category:'反劫机处置', usage:'write' },
{ word:'seize control', meaning:'夺取控制权', phonetic:'/siːz kənˈtrəʊl/', example:'He attempted to seize control of the aircraft.', exampleCn:'他试图夺取飞机的控制权。', category:'反劫机处置', usage:'write' },
{ word:'subdue', meaning:'制伏', phonetic:'/səbˈdjuː/', example:'The security officer helped subdue the attacker.', exampleCn:'航空安全员协助制伏了袭击者。', category:'反劫机处置', usage:'write' },
{ word:'overpower', meaning:'制服 / 压制', phonetic:'/ˌəʊvəˈpaʊə(r)/', example:'Crew members worked together to overpower the hijacker.', exampleCn:'机组成员合力制服了劫机者。', category:'反劫机处置', usage:'write' },
{ word:'silent alarm', meaning:'静默警报', phonetic:'/ˈsaɪlənt əˈlɑːm/', example:'Activate the silent alarm to alert the cockpit.', exampleCn:'启动静默警报以通知驾驶舱。', category:'反劫机处置', usage:'radio' },
{ word:'code word', meaning:'暗语 / 代号', phonetic:'/kəʊd wɜːd/', example:'Use the code word to alert the crew discreetly.', exampleCn:'使用暗语悄悄提醒机组。', category:'反劫机处置', usage:'radio' },
{ word:'lock the cockpit door', meaning:'锁闭驾驶舱门', phonetic:'/lɒk ðə ˈkɒkpɪt dɔː(r)/', example:'Lock the cockpit door immediately.', exampleCn:'立即锁闭驾驶舱门。', category:'反劫机处置', usage:'radio' },
{ word:'improvised weapon', meaning:'临时凶器', phonetic:'/ˈɪmprəvaɪzd ˈwepən/', example:'The passenger used an improvised weapon.', exampleCn:'该旅客使用了临时凶器。', category:'反劫机处置', usage:'write' },
{ word:'neutralize', meaning:'制止 / 消除威胁', phonetic:'/ˈnjuːtrəlaɪz/', example:'The threat was neutralized within minutes.', exampleCn:'该威胁在几分钟内被制止。', category:'反劫机处置', usage:'write' },
{ word:'coordinated response', meaning:'协同处置', phonetic:'/kəʊˈɔːdɪneɪtɪd rɪˈspɒns/', example:'A coordinated response is required from all crew.', exampleCn:'需要全体机组进行协同处置。', category:'反劫机处置', usage:'write' },
{ word:'chain of command', meaning:'指挥链', phonetic:'/tʃeɪn əv kəˈmɑːnd/', example:'Follow the chain of command during a crisis.', exampleCn:'危机期间请遵循指挥链。', category:'反劫机处置', usage:'write' },
/* ---------- 爆炸物威胁 ---------- */
{ word:'bomb threat', meaning:'炸弹威胁', phonetic:'/bɒm θret/', example:'We received a bomb threat before departure.', exampleCn:'起飞前我们收到了炸弹威胁。', category:'爆炸物威胁', usage:'radio' },
{ word:'explosive device', meaning:'爆炸装置', phonetic:'/ɪkˈspləʊsɪv dɪˈvaɪs/', example:'A suspected explosive device was found in the lavatory.', exampleCn:'在洗手间发现疑似爆炸装置。', category:'爆炸物威胁', usage:'radio' },
{ word:'suspicious package', meaning:'可疑包裹', phonetic:'/səˈspɪʃəs ˈpækɪdʒ/', example:'Do not touch the suspicious package.', exampleCn:'请勿触碰可疑包裹。', category:'爆炸物威胁', usage:'face' },
{ word:'evacuate the area', meaning:'疏散该区域', phonetic:'/ɪˈvækjueɪt ði ˈeəriə/', example:'Evacuate the area immediately.', exampleCn:'立即疏散该区域。', category:'爆炸物威胁', usage:'radio' },
{ word:'blast radius', meaning:'爆炸范围', phonetic:'/blɑːst ˈreɪdiəs/', example:'Keep passengers outside the estimated blast radius.', exampleCn:'让旅客远离预估的爆炸范围。', category:'爆炸物威胁', usage:'write' },
{ word:'bomb disposal', meaning:'爆炸物处置', phonetic:'/bɒm dɪˈspəʊzl/', example:'The bomb disposal unit was called to the gate.', exampleCn:'爆炸物处置小组已被叫到登机口。', category:'爆炸物威胁', usage:'write' },
{ word:'containment area', meaning:'隔离/围控区域', phonetic:'/kənˈteɪnmənt ˈeəriə/', example:'Set up a containment area around the item.', exampleCn:'在该物品周围设置隔离区域。', category:'爆炸物威胁', usage:'write' },
{ word:'do not touch', meaning:'请勿触碰', phonetic:'/duː nɒt tʌtʃ/', example:'Do not touch, step away calmly.', exampleCn:'请勿触碰，冷静离开。', category:'爆炸物威胁', usage:'face' },
{ word:'trigger mechanism', meaning:'引爆装置', phonetic:'/ˈtrɪɡə(r) ˈmekənɪzəm/', example:'Never attempt to disarm a trigger mechanism yourself.', exampleCn:'切勿自行尝试拆除引爆装置。', category:'爆炸物威胁', usage:'write' },
{ word:'credible threat', meaning:'可信威胁', phonetic:'/ˈkredəbl θret/', example:'The captain assessed it as a credible threat.', exampleCn:'机长评估此为可信威胁。', category:'爆炸物威胁', usage:'write' },
/* ---------- 无线电通话 ---------- */
{ word:'radio check', meaning:'通信检查', phonetic:'/ˈreɪdiəʊ tʃek/', example:'Radio check, do you copy?', exampleCn:'通信检查，收到吗？', category:'无线电通话', usage:'radio' },
{ word:'copy that', meaning:'收到 / 明白', phonetic:'/ˈkɒpi ðæt/', example:'Copy that, proceeding to row 24.', exampleCn:'收到，正前往24排。', category:'无线电通话', usage:'radio' },
{ word:'roger', meaning:'收到（无线电用语）', phonetic:'/ˈrɒdʒə(r)/', example:'Roger, standing by.', exampleCn:'收到，待命中。', category:'无线电通话', usage:'radio' },
{ word:'stand by', meaning:'待命', phonetic:'/stænd baɪ/', example:'Stand by for further instructions.', exampleCn:'请待命等待进一步指示。', category:'无线电通话', usage:'radio' },
{ word:'say again', meaning:'请重复', phonetic:'/seɪ əˈɡen/', example:'Say again, last transmission was unclear.', exampleCn:'请重复，刚才信号不清楚。', category:'无线电通话', usage:'radio' },
{ word:'go ahead', meaning:'请讲', phonetic:'/ɡəʊ əˈhed/', example:'Go ahead, I am listening.', exampleCn:'请讲，我在听。', category:'无线电通话', usage:'radio' },
{ word:'over', meaning:'（通话结束）完毕', phonetic:'/ˈəʊvə(r)/', example:'Situation under control, over.', exampleCn:'情况已控制，完毕。', category:'无线电通话', usage:'radio' },
{ word:'affirmative', meaning:'确认 / 是的', phonetic:'/əˈfɜːmətɪv/', example:'Affirmative, proceeding now.', exampleCn:'确认，现在开始行动。', category:'无线电通话', usage:'radio' },
{ word:'negative', meaning:'否定 / 不是', phonetic:'/ˈneɡətɪv/', example:'Negative, no injuries reported.', exampleCn:'否定，没有人员受伤报告。', category:'无线电通话', usage:'radio' },
{ word:'break break', meaning:'紧急插播', phonetic:'/breɪk breɪk/', example:'Break break, medical emergency in row 15.', exampleCn:'紧急插播，15排有医疗紧急情况。', category:'无线电通话', usage:'radio' },
{ word:'proceed to', meaning:'前往', phonetic:'/prəˈsiːd tuː/', example:'Proceed to the rear galley now.', exampleCn:'现在前往后厨房区。', category:'无线电通话', usage:'radio' },
{ word:'position report', meaning:'位置报告', phonetic:'/pəˈzɪʃn rɪˈpɔːt/', example:'Give a position report every five minutes.', exampleCn:'每五分钟报告一次位置。', category:'无线电通话', usage:'radio' },
/* ---------- 客舱广播用语 ---------- */
{ word:'ladies and gentlemen', meaning:'女士们先生们', phonetic:'/ˈleɪdiz ənd ˈdʒentlmən/', example:'Ladies and gentlemen, may I have your attention.', exampleCn:'女士们先生们，请注意。', category:'客舱广播用语', usage:'radio' },
{ word:'attention please', meaning:'请注意', phonetic:'/əˈtenʃn pliːz/', example:'Attention please, this is a security announcement.', exampleCn:'请注意，这是一条安全广播。', category:'客舱广播用语', usage:'radio' },
{ word:'for your safety', meaning:'为了您的安全', phonetic:'/fɔː jɔː ˈseɪfti/', example:'For your safety, please remain seated.', exampleCn:'为了您的安全，请保持就座。', category:'客舱广播用语', usage:'radio' },
{ word:'as a reminder', meaning:'提醒您', phonetic:'/æz ə rɪˈmaɪndə(r)/', example:'As a reminder, smoking is prohibited onboard.', exampleCn:'提醒您，机上禁止吸烟。', category:'客舱广播用语', usage:'radio' },
{ word:'thank you for your cooperation', meaning:'感谢您的配合', phonetic:'/θæŋk juː fɔː jɔː kəʊˌɒpəˈreɪʃn/', example:'Thank you for your cooperation.', exampleCn:'感谢您的配合。', category:'客舱广播用语', usage:'radio' },
{ word:'we apologize for the inconvenience', meaning:'对造成的不便深表歉意', phonetic:'/wiː əˈpɒlədʒaɪz fɔː ði ɪnkənˈviːniəns/', example:'We apologize for the inconvenience this may cause.', exampleCn:'对此可能造成的不便深表歉意。', category:'客舱广播用语', usage:'radio' },
{ word:'no smoking is permitted', meaning:'禁止吸烟', phonetic:'/nəʊ ˈsməʊkɪŋ ɪz pəˈmɪtɪd/', example:'No smoking is permitted at any time.', exampleCn:'任何时候都禁止吸烟。', category:'客舱广播用语', usage:'radio' },
/* ---------- 涉外人身检查 ---------- */
{ word:'same-gender search', meaning:'同性别检查', phonetic:'/seɪm ˈdʒendə(r) sɜːtʃ/', example:'A same-gender search will be conducted for privacy.', exampleCn:'为保护隐私将进行同性别检查。', category:'涉外人身检查', usage:'write' },
{ word:'consent', meaning:'同意', phonetic:'/kənˈsent/', example:'Please give your consent before the search.', exampleCn:'检查前请给予您的同意。', category:'涉外人身检查', usage:'face' },
{ word:'privacy screen', meaning:'隐私遮挡', phonetic:'/ˈprɪvəsi skriːn/', example:'The search will be conducted behind a privacy screen.', exampleCn:'检查将在隐私遮挡后进行。', category:'涉外人身检查', usage:'write' },
{ word:'witness officer', meaning:'见证人员', phonetic:'/ˈwɪtnəs ˈɒfɪsə(r)/', example:'A witness officer must be present during the search.', exampleCn:'检查期间必须有一名见证人员在场。', category:'涉外人身检查', usage:'write' },
{ word:'cultural sensitivity', meaning:'文化敏感性', phonetic:'/ˈkʌltʃərəl ˌsensəˈtɪvəti/', example:'Handle the search with cultural sensitivity.', exampleCn:'处理检查时请注意文化敏感性。', category:'涉外人身检查', usage:'write' },
{ word:'religious garment', meaning:'宗教服饰', phonetic:'/rɪˈlɪdʒəs ˈɡɑːmənt/', example:'Special procedures apply when checking a religious garment.', exampleCn:'检查宗教服饰时适用特殊流程。', category:'涉外人身检查', usage:'write' },
{ word:'interpreter', meaning:'翻译人员', phonetic:'/ɪnˈtɜːprɪtə(r)/', example:'Please arrange an interpreter for the passenger.', exampleCn:'请为该旅客安排一名翻译人员。', category:'涉外人身检查', usage:'write' },
{ word:'foreign national', meaning:'外籍人员', phonetic:'/ˈfɒrən ˈnæʃnəl/', example:'The detained person is a foreign national.', exampleCn:'该被扣留人员是外籍人员。', category:'涉外人身检查', usage:'write' },
{ word:'diplomatic immunity', meaning:'外交豁免权', phonetic:'/ˌdɪpləˈmætɪk ɪˈmjuːnəti/', example:'He claims diplomatic immunity.', exampleCn:'他声称拥有外交豁免权。', category:'涉外人身检查', usage:'write' },
/* ---------- 机场公安交接 ---------- */
{ word:'handover procedure', meaning:'交接程序', phonetic:'/ˈhændəʊvə(r) prəˈsiːdʒə(r)/', example:'Follow the handover procedure precisely.', exampleCn:'请精确执行交接程序。', category:'机场公安交接', usage:'write' },
{ word:'evidence bag', meaning:'证物袋', phonetic:'/ˈevɪdəns bæɡ/', example:'Place the item in an evidence bag.', exampleCn:'将该物品放入证物袋。', category:'机场公安交接', usage:'write' },
{ word:'chain of custody', meaning:'证据保管链', phonetic:'/tʃeɪn əv ˈkʌstədi/', example:'Maintain the chain of custody for all evidence.', exampleCn:'对所有证据保持证据保管链。', category:'机场公安交接', usage:'write' },
{ word:'statement', meaning:'陈述 / 笔录', phonetic:'/ˈsteɪtmənt/', example:'The witness gave a written statement.', exampleCn:'目击者提供了一份书面陈述。', category:'机场公安交接', usage:'write' },
{ word:'sign the report', meaning:'在报告上签字', phonetic:'/saɪn ðə rɪˈpɔːt/', example:'Please sign the report to confirm the details.', exampleCn:'请在报告上签字以确认细节。', category:'机场公安交接', usage:'face' },
{ word:'airport police', meaning:'机场公安', phonetic:'/ˈeəpɔːt pəˈliːs/', example:'Airport police are waiting at the gate.', exampleCn:'机场公安正在登机口等候。', category:'机场公安交接', usage:'radio' },
{ word:'formal complaint', meaning:'正式投诉', phonetic:'/ˈfɔːml kəmˈpleɪnt/', example:'The passenger filed a formal complaint.', exampleCn:'该旅客提交了一份正式投诉。', category:'机场公安交接', usage:'write' },
{ word:'transfer custody', meaning:'移交监管', phonetic:'/ˈtrænsfɜː(r) ˈkʌstədi/', example:'We will transfer custody to the police on landing.', exampleCn:'落地后我们将向警方移交监管。', category:'机场公安交接', usage:'write' },
/* ---------- 涉毒特情 ---------- */
{ word:'illegal drugs', meaning:'违禁毒品', phonetic:'/ɪˈliːɡl drʌɡz/', example:'Illegal drugs were found in the carry-on bag.', exampleCn:'在随身行李中发现了违禁毒品。', category:'涉毒特情', usage:'write' },
{ word:'narcotics', meaning:'麻醉品 / 毒品', phonetic:'/nɑːˈkɒtɪks/', example:'The dog alerted to possible narcotics.', exampleCn:'警犬对可疑毒品发出了警示。', category:'涉毒特情', usage:'write' },
{ word:'smuggling', meaning:'走私', phonetic:'/ˈsmʌɡlɪŋ/', example:'This may be a case of smuggling.', exampleCn:'这可能是一起走私案件。', category:'涉毒特情', usage:'write' },
{ word:'concealed substance', meaning:'隐藏物质', phonetic:'/kənˈsiːld ˈsʌbstəns/', example:'A concealed substance was discovered during the search.', exampleCn:'检查中发现了隐藏物质。', category:'涉毒特情', usage:'write' },
{ word:'controlled substance', meaning:'管制物品/物质', phonetic:'/kənˈtrəʊld ˈsʌbstəns/', example:'This is classified as a controlled substance.', exampleCn:'这被归类为管制物质。', category:'涉毒特情', usage:'write' },
{ word:'drug-sniffing dog', meaning:'缉毒犬', phonetic:'/drʌɡ ˈsnɪfɪŋ dɒɡ/', example:'A drug-sniffing dog checked the cargo area.', exampleCn:'一只缉毒犬检查了货舱区域。', category:'涉毒特情', usage:'write' },
{ word:'possession', meaning:'持有（违禁品）', phonetic:'/pəˈzeʃn/', example:'He was found in possession of a controlled substance.', exampleCn:'他被发现持有管制物质。', category:'涉毒特情', usage:'write' },
/* ---------- 涉恐特情 ---------- */
{ word:'terrorist threat', meaning:'恐怖威胁', phonetic:'/ˈterərɪst θret/', example:'The captain was informed of a terrorist threat.', exampleCn:'机长已被告知一起恐怖威胁。', category:'涉恐特情', usage:'write' },
{ word:'extremist material', meaning:'极端主义材料', phonetic:'/ɪkˈstriːmɪst məˈtɪəriəl/', example:'Extremist material was found on his phone.', exampleCn:'在他的手机中发现了极端主义材料。', category:'涉恐特情', usage:'write' },
{ word:'watchlist', meaning:'监控名单', phonetic:'/ˈwɒtʃlɪst/', example:'The passenger name matched the watchlist.', exampleCn:'该旅客姓名与监控名单匹配。', category:'涉恐特情', usage:'write' },
{ word:'no-fly list', meaning:'禁飞名单', phonetic:'/nəʊ flaɪ lɪst/', example:'His name appeared on the no-fly list.', exampleCn:'他的名字出现在禁飞名单上。', category:'涉恐特情', usage:'write' },
{ word:'suspicious behavior', meaning:'可疑行为', phonetic:'/səˈspɪʃəs bɪˈheɪvjə(r)/', example:'Report any suspicious behavior immediately.', exampleCn:'如发现任何可疑行为请立即报告。', category:'涉恐特情', usage:'radio' },
{ word:'intelligence report', meaning:'情报通报', phonetic:'/ɪnˈtelɪdʒəns rɪˈpɔːt/', example:'An intelligence report warned of possible threats.', exampleCn:'一份情报通报警告了可能的威胁。', category:'涉恐特情', usage:'write' },
{ word:'heightened alert', meaning:'高度戒备', phonetic:'/ˈhaɪtnd əˈlɜːt/', example:'The crew is on heightened alert today.', exampleCn:'机组今天处于高度戒备状态。', category:'涉恐特情', usage:'write' },
/* ---------- 醉酒精神异常 ---------- */
{ word:'intoxicated', meaning:'醉酒的', phonetic:'/ɪnˈtɒksɪkeɪtɪd/', example:'The passenger appeared heavily intoxicated.', exampleCn:'该旅客看起来严重醉酒。', category:'醉酒精神异常', usage:'write' },
{ word:'slurred speech', meaning:'言语含糊', phonetic:'/slɜːd spiːtʃ/', example:'He showed slurred speech and unsteady walking.', exampleCn:'他表现出言语含糊和走路不稳。', category:'醉酒精神异常', usage:'write' },
{ word:'erratic behavior', meaning:'反常行为', phonetic:'/ɪˈrætɪk bɪˈheɪvjə(r)/', example:'Erratic behavior was noticed before boarding.', exampleCn:'登机前注意到了反常行为。', category:'醉酒精神异常', usage:'write' },
{ word:'mental distress', meaning:'精神/情绪异常', phonetic:'/ˈmentl dɪˈstres/', example:'The passenger appeared to be in mental distress.', exampleCn:'该旅客似乎处于精神异常状态。', category:'醉酒精神异常', usage:'write' },
{ word:'refuse alcohol service', meaning:'拒绝提供酒精饮品', phonetic:'/rɪˈfjuːz ˈælkəhɒl ˈsɜːvɪs/', example:'The crew can refuse alcohol service to an intoxicated passenger.', exampleCn:'机组可对醉酒旅客拒绝提供酒精饮品。', category:'醉酒精神异常', usage:'write' },
{ word:'de-escalate', meaning:'降级处理 / 缓和局势', phonetic:'/diː ˈeskəleɪt/', example:'Try to de-escalate the situation calmly.', exampleCn:'请尝试冷静地缓和局势。', category:'醉酒精神异常', usage:'write' },
{ word:'sedate', meaning:'使镇静', phonetic:'/sɪˈdeɪt/', example:'A doctor onboard offered to sedate the passenger.', exampleCn:'机上一名医生提出为该旅客使用镇静药物。', category:'醉酒精神异常', usage:'write' },
/* ---------- VIP外交服务 ---------- */
{ word:'VIP passenger', meaning:'重要旅客', phonetic:'/ˌviː aɪ ˈpiː ˈpæsɪndʒə(r)/', example:'The VIP passenger will board first.', exampleCn:'重要旅客将优先登机。', category:'VIP外交服务', usage:'face' },
{ word:'diplomatic pouch', meaning:'外交邮袋', phonetic:'/ˌdɪpləˈmætɪk paʊtʃ/', example:'The diplomatic pouch cannot be opened or inspected.', exampleCn:'外交邮袋不得开启或检查。', category:'VIP外交服务', usage:'write' },
{ word:'protocol officer', meaning:'礼宾官员', phonetic:'/ˈprəʊtəkɒl ˈɒfɪsə(r)/', example:'A protocol officer accompanied the delegation.', exampleCn:'一名礼宾官员陪同了代表团。', category:'VIP外交服务', usage:'write' },
{ word:'courtesy', meaning:'礼节 / 礼貌', phonetic:'/ˈkɜːtəsi/', example:'Treat all VIP guests with courtesy.', exampleCn:'请以礼貌对待所有贵宾。', category:'VIP外交服务', usage:'face' },
{ word:'delegation', meaning:'代表团', phonetic:'/ˌdelɪˈɡeɪʃn/', example:'A government delegation is on this flight.', exampleCn:'一个政府代表团在本次航班上。', category:'VIP外交服务', usage:'write' },
/* ---------- 投诉服务补救 ---------- */
{ word:'complaint handling', meaning:'投诉处理', phonetic:'/kəmˈpleɪnt ˈhændlɪŋ/', example:'Complaint handling should be prompt and professional.', exampleCn:'投诉处理应及时且专业。', category:'投诉服务补救', usage:'write' },
{ word:'service recovery', meaning:'服务补救', phonetic:'/ˈsɜːvɪs rɪˈkʌvəri/', example:'Service recovery is important after any incident.', exampleCn:'事件发生后进行服务补救很重要。', category:'投诉服务补救', usage:'write' },
{ word:'sincere apology', meaning:'真诚道歉', phonetic:'/sɪnˈsɪə(r) əˈpɒlədʒi/', example:'Please accept our sincere apology.', exampleCn:'请接受我们真诚的道歉。', category:'投诉服务补救', usage:'face' },
{ word:'misunderstanding', meaning:'误会', phonetic:'/ˌmɪsʌndəˈstændɪŋ/', example:'I believe this was a misunderstanding.', exampleCn:'我认为这是一场误会。', category:'投诉服务补救', usage:'face' },
{ word:'reasonable explanation', meaning:'合理解释', phonetic:'/ˈriːznəbl ˌekspləˈneɪʃn/', example:'Let me give you a reasonable explanation.', exampleCn:'让我给您一个合理的解释。', category:'投诉服务补救', usage:'face' },
{ word:'escalate the complaint', meaning:'升级投诉', phonetic:'/ˈeskəleɪt ðə kəmˈpleɪnt/', example:'The passenger threatened to escalate the complaint.', exampleCn:'该旅客威胁要升级投诉。', category:'投诉服务补救', usage:'write' },
{ word:'compensation', meaning:'补偿', phonetic:'/ˌkɒmpenˈseɪʃn/', example:'The airline offered compensation for the delay.', exampleCn:'航空公司为延误提供了补偿。', category:'投诉服务补救', usage:'face' },
{ word:'goodwill gesture', meaning:'善意表示', phonetic:'/ˈɡʊdwɪl ˈdʒestʃə(r)/', example:'We offer this as a goodwill gesture.', exampleCn:'我们提供此项作为善意表示。', category:'投诉服务补救', usage:'face' },
/* ---------- 医疗急救 ---------- */
{ word:'hospital', meaning:'医院', phonetic:'/ˈhɒspɪtl/', example:'I need to go to the hospital.', exampleCn:'我需要去医院。', category:'医疗急救', usage:'life' },
{ word:'ambulance', meaning:'救护车', phonetic:'/ˈæmbjələns/', example:'Call an ambulance immediately.', exampleCn:'立即叫救护车。', category:'医疗急救', usage:'radio' },
{ word:'first aid', meaning:'急救', phonetic:'/fɜːst eɪd/', example:'We need first aid immediately.', exampleCn:'我们需要立即急救。', category:'医疗急救', usage:'radio' },
{ word:'CPR', meaning:'心肺复苏', phonetic:'/ˌsiː piː ˈɑː(r)/', example:'The officer performed CPR until landing.', exampleCn:'安全员一直进行心肺复苏直到落地。', category:'医疗急救', usage:'write' },
{ word:'defibrillator', meaning:'自动体外除颤器', phonetic:'/dɪˈfɪbrɪleɪtə(r)/', example:'Bring the defibrillator to seat 22C.', exampleCn:'把自动体外除颤器带到22C座位。', category:'医疗急救', usage:'radio' },
{ word:'unconscious', meaning:'失去意识的', phonetic:'/ʌnˈkɒnʃəs/', example:'The passenger became unconscious suddenly.', exampleCn:'该旅客突然失去了意识。', category:'医疗急救', usage:'radio' },
{ word:'is there a doctor onboard', meaning:'机上是否有医生', phonetic:'/ɪz ðeər ə ˈdɒktər ɒnˈbɔːd/', example:'Is there a doctor onboard? We need assistance.', exampleCn:'机上是否有医生？我们需要帮助。', category:'医疗急救', usage:'radio' },
{ word:'pulse', meaning:'脉搏', phonetic:'/pʌls/', example:'Check the passenger’s pulse.', exampleCn:'检查该旅客的脉搏。', category:'医疗急救', usage:'write' },
{ word:'seizure', meaning:'癫痫发作', phonetic:'/ˈsiːʒə(r)/', example:'The passenger is having a seizure.', exampleCn:'该旅客正在癫痫发作。', category:'医疗急救', usage:'radio' },
{ word:'medical kit', meaning:'医疗急救箱', phonetic:'/ˈmedɪkl kɪt/', example:'Bring the medical kit from the front galley.', exampleCn:'把医疗急救箱从前厨房区带过来。', category:'医疗急救', usage:'radio' },
{ word:'allergic reaction', meaning:'过敏反应', phonetic:'/əˈlɜːdʒɪk riˈækʃn/', example:'The passenger is having an allergic reaction.', exampleCn:'该旅客出现了过敏反应。', category:'医疗急救', usage:'radio' },
{ word:'fainting', meaning:'昏厥', phonetic:'/ˈfeɪntɪŋ/', example:'She reported dizziness before fainting.', exampleCn:'她昏厥前报告了头晕。', category:'医疗急救', usage:'write' },
/* ---------- 驾驶舱门安全 ---------- */
{ word:'cockpit', meaning:'驾驶舱', phonetic:'/ˈkɒkpɪt/', example:'Do not approach the cockpit.', exampleCn:'请勿靠近驾驶舱。', category:'驾驶舱门安全', usage:'face' },
{ word:'cockpit door', meaning:'驾驶舱门', phonetic:'/ˈkɒkpɪt dɔː(r)/', example:'The cockpit door must remain locked.', exampleCn:'驾驶舱门必须保持锁定。', category:'驾驶舱门安全', usage:'write' },
{ word:'reinforced door', meaning:'加固舱门', phonetic:'/ˌriːɪnˈfɔːst dɔː(r)/', example:'The reinforced door prevents forced entry.', exampleCn:'加固舱门可防止强行进入。', category:'驾驶舱门安全', usage:'write' },
{ word:'entry code', meaning:'进入密码', phonetic:'/ˈentri kəʊd/', example:'Only authorized crew know the entry code.', exampleCn:'只有授权机组人员知道进入密码。', category:'驾驶舱门安全', usage:'write' },
{ word:'two-person rule', meaning:'双人原则', phonetic:'/tuː ˈpɜːsn ruːl/', example:'The two-person rule applies whenever the door is open.', exampleCn:'舱门开启时始终适用双人原则。', category:'驾驶舱门安全', usage:'write' },
{ word:'crew rest area', meaning:'机组休息区', phonetic:'/kruː rest ˈeəriə/', example:'Access to the crew rest area is restricted.', exampleCn:'机组休息区的进入受到限制。', category:'驾驶舱门安全', usage:'write' },
/* ---------- 危险品细化 ---------- */
{ word:'flammable liquid', meaning:'易燃液体', phonetic:'/ˈflæməbl ˈlɪkwɪd/', example:'Flammable liquids are not allowed onboard.', exampleCn:'易燃液体不允许携带上机。', category:'危险品细化', usage:'face' },
{ word:'lithium battery', meaning:'锂电池', phonetic:'/ˈlɪθiəm ˈbætəri/', example:'Spare lithium batteries must be carried in cabin baggage.', exampleCn:'备用锂电池必须放在随身行李中携带。', category:'危险品细化', usage:'face' },
{ word:'compressed gas', meaning:'压缩气体', phonetic:'/kəmˈprest ɡæs/', example:'Compressed gas canisters are prohibited.', exampleCn:'压缩气体罐是禁止携带的。', category:'危险品细化', usage:'face' },
{ word:'corrosive substance', meaning:'腐蚀性物质', phonetic:'/kəˈrəʊsɪv ˈsʌbstəns/', example:'A corrosive substance was found in checked baggage.', exampleCn:'在托运行李中发现了腐蚀性物质。', category:'危险品细化', usage:'write' },
{ word:'sharp object', meaning:'锐器', phonetic:'/ʃɑːp ˈɒbdʒɪkt/', example:'Sharp objects must go in checked baggage.', exampleCn:'锐器必须放入托运行李。', category:'危险品细化', usage:'face' },
{ word:'firearm', meaning:'枪支', phonetic:'/ˈfaɪərɑːm/', example:'Any firearm must be declared before check-in.', exampleCn:'任何枪支都必须在办理登机前申报。', category:'危险品细化', usage:'write' },
{ word:'ammunition', meaning:'弹药', phonetic:'/ˌæmjuˈnɪʃn/', example:'Ammunition is strictly regulated on flights.', exampleCn:'弹药在航班上受到严格管制。', category:'危险品细化', usage:'write' },
{ word:'declare', meaning:'申报', phonetic:'/dɪˈkleə(r)/', example:'You must declare all dangerous goods.', exampleCn:'您必须申报所有危险品。', category:'危险品细化', usage:'face' },
{ word:'confiscate', meaning:'没收', phonetic:'/ˈkɒnfɪskeɪt/', example:'The item will be confiscated.', exampleCn:'该物品将被没收。', category:'危险品细化', usage:'face' },
/* ---------- 客舱设施扩展 ---------- */
{ word:'reading light', meaning:'阅读灯', phonetic:'/ˈriːdɪŋ laɪt/', example:'The reading light above seat 14A is broken.', exampleCn:'14A座位上方的阅读灯坏了。', category:'客舱设施扩展', usage:'life' },
{ word:'call button', meaning:'呼叫按钮', phonetic:'/kɔːl ˈbʌtn/', example:'Press the call button if you need help.', exampleCn:'如需帮助请按呼叫按钮。', category:'客舱设施扩展', usage:'life' },
{ word:'tray table', meaning:'小桌板', phonetic:'/treɪ ˈteɪbl/', example:'Please stow your tray table for landing.', exampleCn:'着陆前请收好小桌板。', category:'客舱设施扩展', usage:'face' },
{ word:'window shade', meaning:'遮光板', phonetic:'/ˈwɪndəʊ ʃeɪd/', example:'Please open your window shade for takeoff.', exampleCn:'起飞时请打开遮光板。', category:'客舱设施扩展', usage:'face' },
{ word:'headrest', meaning:'头枕', phonetic:'/ˈhedrest/', example:'Adjust your headrest for comfort.', exampleCn:'请调整头枕以获得舒适感。', category:'客舱设施扩展', usage:'life' },
/* ---------- 天气与延误 ---------- */
{ word:'flight delay', meaning:'航班延误', phonetic:'/flaɪt dɪˈleɪ/', example:'The flight delay was caused by bad weather.', exampleCn:'航班延误是由恶劣天气造成的。', category:'天气与延误', usage:'face' },
{ word:'turbulence', meaning:'气流颠簸', phonetic:'/ˈtɜːbjələns/', example:'We are expecting turbulence ahead.', exampleCn:'我们预计前方会有气流颠簸。', category:'天气与延误', usage:'radio' },
{ word:'thunderstorm', meaning:'雷暴', phonetic:'/ˈθʌndəstɔːm/', example:'The flight was delayed due to a thunderstorm.', exampleCn:'航班因雷暴而延误。', category:'天气与延误', usage:'face' },
{ word:'diversion', meaning:'备降', phonetic:'/daɪˈvɜːʒn/', example:'A diversion may be necessary due to fuel levels.', exampleCn:'由于燃油情况可能需要备降。', category:'天气与延误', usage:'radio' },
{ word:'ground stop', meaning:'地面停飞', phonetic:'/ɡraʊnd stɒp/', example:'A ground stop has been issued at the destination airport.', exampleCn:'目的地机场已发布地面停飞指令。', category:'天气与延误', usage:'write' },
{ word:'cancelled flight', meaning:'取消的航班', phonetic:'/ˈkænsld flaɪt/', example:'Passengers on the cancelled flight need rebooking.', exampleCn:'被取消航班的旅客需要重新订票。', category:'天气与延误', usage:'face' },
/* ---------- 出入境海关扩展 ---------- */
{ word:'customs declaration', meaning:'海关申报', phonetic:'/ˈkʌstəmz ˌdekləˈreɪʃn/', example:'Please complete your customs declaration form.', exampleCn:'请填写海关申报单。', category:'出入境海关扩展', usage:'face' },
{ word:'immigration counter', meaning:'边检柜台', phonetic:'/ˌɪmɪˈɡreɪʃn ˈkaʊntə(r)/', example:'Proceed to the immigration counter.', exampleCn:'请前往边检柜台。', category:'出入境海关扩展', usage:'face' },
{ word:'entry stamp', meaning:'入境印章', phonetic:'/ˈentri stæmp/', example:'Make sure you get an entry stamp in your passport.', exampleCn:'请确保护照上盖有入境印章。', category:'出入境海关扩展', usage:'life' },
{ word:'quarantine', meaning:'检疫', phonetic:'/ˈkwɒrəntiːn/', example:'Certain food items are subject to quarantine.', exampleCn:'某些食品受检疫限制。', category:'出入境海关扩展', usage:'face' },
{ word:'duty-free', meaning:'免税的', phonetic:'/ˈdjuːti friː/', example:'You may buy duty-free goods after security.', exampleCn:'通过安检后您可以购买免税商品。', category:'出入境海关扩展', usage:'life' },
{ word:'transit visa', meaning:'过境签证', phonetic:'/ˈtrænzɪt ˈviːzə/', example:'Some countries require a transit visa.', exampleCn:'部分国家要求持有过境签证。', category:'出入境海关扩展', usage:'life' },
/* ---------- 通讯网络出境 ---------- */
{ word:'Wi-Fi password', meaning:'无线网络密码', phonetic:'/ˈwaɪfaɪ ˈpɑːswɜːd/', example:'Could you give me the Wi-Fi password?', exampleCn:'能给我无线网络密码吗？', category:'通讯网络出境', usage:'life' },
{ word:'SIM card', meaning:'手机卡', phonetic:'/sɪm kɑːd/', example:'I need to buy a local SIM card.', exampleCn:'我需要买一张当地的手机卡。', category:'通讯网络出境', usage:'life' },
{ word:'roaming', meaning:'漫游', phonetic:'/ˈrəʊmɪŋ/', example:'International roaming charges may apply.', exampleCn:'可能会产生国际漫游费用。', category:'通讯网络出境', usage:'life' },
{ word:'charger', meaning:'充电器', phonetic:'/ˈtʃɑːdʒə(r)/', example:'Do you have a spare charger?', exampleCn:'你有多余的充电器吗？', category:'通讯网络出境', usage:'life' },
{ word:'power adapter', meaning:'电源转换插头', phonetic:'/ˈpaʊər əˈdæptə(r)/', example:'I need a power adapter for this country.', exampleCn:'我需要这个国家的电源转换插头。', category:'通讯网络出境', usage:'life' },
/* ---------- 银行金融出境 ---------- */
{ word:'exchange rate', meaning:'汇率', phonetic:'/ɪksˈtʃeɪndʒ reɪt/', example:'What is the exchange rate today?', exampleCn:'今天的汇率是多少？', category:'银行金融出境', usage:'life' },
{ word:'currency', meaning:'货币', phonetic:'/ˈkʌrənsi/', example:'What currency do you accept?', exampleCn:'你们接受什么货币？', category:'银行金融出境', usage:'life' },
{ word:'ATM', meaning:'自动取款机', phonetic:'/ˌeɪ tiː ˈem/', example:'Is there an ATM nearby?', exampleCn:'附近有自动取款机吗？', category:'银行金融出境', usage:'life' },
{ word:'withdraw cash', meaning:'取现', phonetic:'/wɪðˈdrɔː kæʃ/', example:'I would like to withdraw some cash.', exampleCn:'我想取一些现金。', category:'银行金融出境', usage:'life' },
{ word:'wire transfer', meaning:'电汇', phonetic:'/waɪə(r) ˈtrænsfɜː(r)/', example:'I need to make a wire transfer.', exampleCn:'我需要办理一笔电汇。', category:'银行金融出境', usage:'life' },
/* ---------- 时间数字方位 ---------- */
{ word:'immediately', meaning:'立即', phonetic:'/ɪˈmiːdiətli/', example:'Report to the cockpit immediately.', exampleCn:'立即向驾驶舱报告。', category:'时间数字方位', usage:'radio' },
{ word:'in five minutes', meaning:'五分钟内', phonetic:'/ɪn faɪv ˈmɪnɪts/', example:'We will land in five minutes.', exampleCn:'我们将在五分钟内降落。', category:'时间数字方位', usage:'radio' },
{ word:'to your left', meaning:'在您左边', phonetic:'/tə jɔː left/', example:'The exit is to your left.', exampleCn:'出口在您左边。', category:'时间数字方位', usage:'face' },
{ word:'to your right', meaning:'在您右边', phonetic:'/tə jɔː raɪt/', example:'Row 30 is to your right.', exampleCn:'30排在您右边。', category:'时间数字方位', usage:'face' },
{ word:'row number', meaning:'排号', phonetic:'/rəʊ ˈnʌmbə(r)/', example:'What is your row number?', exampleCn:'您的排号是多少？', category:'时间数字方位', usage:'face' },
{ word:'seat number', meaning:'座位号', phonetic:'/siːt ˈnʌmbə(r)/', example:'Please check your seat number.', exampleCn:'请查看您的座位号。', category:'时间数字方位', usage:'face' },
/* ---------- 身体部位伤情 ---------- */
{ word:'injury', meaning:'伤害 / 受伤', phonetic:'/ˈɪndʒəri/', example:'The passenger suffered an injury.', exampleCn:'该旅客受了伤。', category:'身体部位伤情', usage:'write' },
{ word:'bleeding', meaning:'出血', phonetic:'/ˈbliːdɪŋ/', example:'The passenger is bleeding.', exampleCn:'该旅客在出血。', category:'身体部位伤情', usage:'radio' },
{ word:'fracture', meaning:'骨折', phonetic:'/ˈfræktʃə(r)/', example:'The doctor suspects a fracture.', exampleCn:'医生怀疑是骨折。', category:'身体部位伤情', usage:'write' },
{ word:'bruise', meaning:'瘀伤', phonetic:'/bruːz/', example:'There is a bruise on his arm.', exampleCn:'他的手臂上有一处瘀伤。', category:'身体部位伤情', usage:'write' },
{ word:'swelling', meaning:'肿胀', phonetic:'/ˈswelɪŋ/', example:'There is noticeable swelling around the ankle.', exampleCn:'脚踝周围有明显的肿胀。', category:'身体部位伤情', usage:'write' },
{ word:'fever', meaning:'发烧', phonetic:'/ˈfiːvə(r)/', example:'The passenger has a high fever.', exampleCn:'该旅客发高烧了。', category:'身体部位伤情', usage:'write' },
{ word:'symptom', meaning:'症状', phonetic:'/ˈsɪmptəm/', example:'What are your symptoms?', exampleCn:'您有什么症状？', category:'身体部位伤情', usage:'face' },
/* ---------- 酒店住宿 ---------- */
{ word:'check-in', meaning:'入住登记', phonetic:'/ˈtʃek ɪn/', example:'Check-in time is 3:00 PM.', exampleCn:'入住时间是下午三点。', category:'酒店住宿', usage:'life' },
{ word:'reservation', meaning:'预订', phonetic:'/ˌrezəˈveɪʃn/', example:'I have a reservation under my name.', exampleCn:'我用我的名字做了预订。', category:'酒店住宿', usage:'life' },
{ word:'room service', meaning:'客房服务', phonetic:'/ruːm ˈsɜːvɪs/', example:'I would like to order room service.', exampleCn:'我想点客房服务。', category:'酒店住宿', usage:'life' },
{ word:'amenity', meaning:'设施 / 便利设施', phonetic:'/əˈmenəti/', example:'The hotel offers many amenities.', exampleCn:'这家酒店提供许多便利设施。', category:'酒店住宿', usage:'life' },
{ word:'key card', meaning:'房卡', phonetic:'/kiː kɑːd/', example:'Here is your key card.', exampleCn:'这是您的房卡。', category:'酒店住宿', usage:'life' },
{ word:'deposit', meaning:'押金', phonetic:'/dɪˈpɒzɪt/', example:'A deposit is required for the room.', exampleCn:'入住需要交押金。', category:'酒店住宿', usage:'life' },
{ word:'checkout', meaning:'退房', phonetic:'/ˈtʃekaʊt/', example:'Checkout time is 12:00 PM.', exampleCn:'退房时间是中午十二点。', category:'酒店住宿', usage:'life' },
{ word:'suite', meaning:'套房', phonetic:'/swiːt/', example:'We booked a suite for our stay.', exampleCn:'我们预订了一间套房。', category:'酒店住宿', usage:'life' },
{ word:'lobby', meaning:'大堂', phonetic:'/ˈlɒbi/', example:'Please meet me in the hotel lobby.', exampleCn:'请在酒店大堂等我。', category:'酒店住宿', usage:'life' },
{ word:'concierge', meaning:'礼宾部 / 前台服务', phonetic:'/ˌkɒnsiˈeəʒ/', example:'The concierge can help you book a tour.', exampleCn:'礼宾部可以帮您预订旅行。', category:'酒店住宿', usage:'life' },
{ word:'wake-up call', meaning:'叫醒电话', phonetic:'/weɪk ʌp kɔːl/', example:'I need a wake-up call at 6:00 AM.', exampleCn:'我需要在早上六点接叫醒电话。', category:'酒店住宿', usage:'life' },
{ word:'laundry', meaning:'洗衣服务', phonetic:'/ˈlɔːndri/', example:'I need to send my clothes to the laundry.', exampleCn:'我需要把衣服送去洗衣。', category:'酒店住宿', usage:'life' },
{ word:'towel', meaning:'毛巾', phonetic:'/ˈtaʊəl/', example:'Can I have an extra towel, please?', exampleCn:'请给我一条额外的毛巾好吗？', category:'酒店住宿', usage:'life' },
{ word:'pillow', meaning:'枕头', phonetic:'/ˈpɪləʊ/', example:'I need an extra pillow.', exampleCn:'我需要一个额外的枕头。', category:'酒店住宿', usage:'life' },
{ word:'air conditioning', meaning:'空调', phonetic:'/eə kənˌdɪʃənɪŋ/', example:'The air conditioning is not working.', exampleCn:'空调不工作了。', category:'酒店住宿', usage:'life' },
/* ---------- 餐饮美食 ---------- */
{ word:'menu', meaning:'菜单', phonetic:'/ˈmenjuː/', example:'May I see the menu, please?', exampleCn:'请给我看一下菜单好吗？', category:'餐饮美食', usage:'life' },
{ word:'appetizer', meaning:'开胃菜', phonetic:'/ˈæpɪtaɪzə(r)/', example:'I would like to order an appetizer.', exampleCn:'我想点一道开胃菜。', category:'餐饮美食', usage:'life' },
{ word:'dessert', meaning:'甜点', phonetic:'/dɪˈzɜːt/', example:'What desserts do you have?', exampleCn:'你们有什么甜点？', category:'餐饮美食', usage:'life' },
{ word:'beverage', meaning:'饮料', phonetic:'/ˈbevərɪdʒ/', example:'What beverages do you offer?', exampleCn:'你们提供什么饮料？', category:'餐饮美食', usage:'life' },
{ word:'tip', meaning:'小费', phonetic:'/tɪp/', example:'Is a tip included in the bill?', exampleCn:'账单包含小费吗？', category:'餐饮美食', usage:'life' },
{ word:'receipt', meaning:'收据', phonetic:'/rɪˈsiːt/', example:'May I have the receipt, please?', exampleCn:'请给我收据好吗？', category:'餐饮美食', usage:'life' },
{ word:'allergy', meaning:'过敏', phonetic:'/ˈælədʒi/', example:'I have a food allergy to peanuts.', exampleCn:'我对花生食物过敏。', category:'餐饮美食', usage:'life' },
{ word:'vegetarian', meaning:'素食', phonetic:'/ˌvedʒəˈteəriən/', example:'Do you have any vegetarian options?', exampleCn:'你们有素食选项吗？', category:'餐饮美食', usage:'life' },
{ word:'ingredients', meaning:'食材 / 成分', phonetic:'/ɪnˈɡriːdiənts/', example:'What ingredients are in this dish?', exampleCn:'这道菜用了什么食材？', category:'餐饮美食', usage:'life' },
{ word:'bill', meaning:'账单', phonetic:'/bɪl/', example:'Could I have the bill, please?', exampleCn:'请把账单给我好吗？', category:'餐饮美食', usage:'life' },
{ word:'order', meaning:'点餐 / 订单', phonetic:'/ˈɔːdə(r)/', example:'I would like to place an order.', exampleCn:'我想点餐。', category:'餐饮美食', usage:'life' },
{ word:'waiter', meaning:'服务员', phonetic:'/ˈweɪtə(r)/', example:'Excuse me, waiter.', exampleCn:'打扰一下，服务员。', category:'餐饮美食', usage:'life' },
{ word:'napkin', meaning:'餐巾', phonetic:'/ˈnæpkɪn/', example:'Could I have a napkin, please?', exampleCn:'请给我一条餐巾好吗？', category:'餐饮美食', usage:'life' },
{ word:'fork', meaning:'叉子', phonetic:'/fɔːk/', example:'May I have a fork?', exampleCn:'可以给我一把叉子吗？', category:'餐饮美食', usage:'life' },
{ word:'knife', meaning:'刀', phonetic:'/naɪf/', example:'Could you bring me a knife?', exampleCn:'能给我一把刀吗？', category:'餐饮美食', usage:'life' },
/* ---------- 交通出行 ---------- */
{ word:'taxi', meaning:'出租车', phonetic:'/ˈtæksi/', example:'Please call a taxi for me.', exampleCn:'请帮我叫一辆出租车。', category:'交通出行', usage:'life' },
{ word:'subway', meaning:'地铁', phonetic:'/ˈsʌbweɪ/', example:'Take the subway to the airport.', exampleCn:'乘地铁去机场。', category:'交通出行', usage:'life' },
{ word:'bus stop', meaning:'公交站', phonetic:'/bʌs stɒp/', example:'Where is the nearest bus stop?', exampleCn:'最近的公交站在哪里？', category:'交通出行', usage:'life' },
{ word:'fare', meaning:'车费', phonetic:'/feə(r)/', example:'How much is the fare?', exampleCn:'车费多少钱？', category:'交通出行', usage:'life' },
{ word:'direction', meaning:'方向 / 路线', phonetic:'/dəˈrekʃn/', example:'Can you give me directions to the hotel?', exampleCn:'您能告诉我去酒店怎么走吗？', category:'交通出行', usage:'life' },
{ word:'intersection', meaning:'十字路口', phonetic:'/ˌɪntəˈsekʃn/', example:'Turn left at the intersection.', exampleCn:'在十字路口左转。', category:'交通出行', usage:'life' },
{ word:'traffic light', meaning:'红绿灯', phonetic:'/ˈtræfɪk laɪt/', example:'Turn right at the traffic light.', exampleCn:'在红绿灯处右转。', category:'交通出行', usage:'life' },
{ word:'transfer', meaning:'换乘 / 中转', phonetic:'/trænsˈfɜː(r)/', example:'Do I need to transfer?', exampleCn:'我需要换乘吗？', category:'交通出行', usage:'life' },
{ word:'schedule', meaning:'时刻表 / 日程', phonetic:'/ˈʃedjuːl/', example:'Check the bus schedule.', exampleCn:'查看公交时刻表。', category:'交通出行', usage:'life' },
{ word:'departure', meaning:'出发 / 离港', phonetic:'/dɪˈpɑːtʃə(r)/', example:'The departure time is 8:00 AM.', exampleCn:'出发时间是早上八点。', category:'交通出行', usage:'life' },
{ word:'arrival', meaning:'到达 / 到港', phonetic:'/əˈraɪvl/', example:'The arrival time is 2:00 PM.', exampleCn:'到达时间是下午两点。', category:'交通出行', usage:'life' },
{ word:'terminal', meaning:'航站楼 / 终点站', phonetic:'/ˈtɜːmɪnl/', example:'Which terminal does the flight leave from?', exampleCn:'航班从哪个航站楼出发？', category:'交通出行', usage:'life' },
{ word:'platform', meaning:'站台', phonetic:'/ˈplætfɔːm/', example:'Go to platform number 3.', exampleCn:'前往三号站台。', category:'交通出行', usage:'life' },
{ word:'ticket', meaning:'车票 / 机票', phonetic:'/ˈtɪkɪt/', example:'I need to buy a ticket.', exampleCn:'我需要买一张票。', category:'交通出行', usage:'life' },
{ word:'commute', meaning:'通勤', phonetic:'/kəˈmjuːt/', example:'I commute to work by subway.', exampleCn:'我乘地铁通勤上班。', category:'交通出行', usage:'life' },
/* ---------- 购物消费 ---------- */
{ word:'discount', meaning:'折扣', phonetic:'/ˈdɪskaʊnt/', example:'Is there a discount on this item?', exampleCn:'这个商品有折扣吗？', category:'购物消费', usage:'life' },
{ word:'size', meaning:'尺码', phonetic:'/saɪz/', example:'What size do you have?', exampleCn:'你们有什么尺码？', category:'购物消费', usage:'life' },
{ word:'fitting room', meaning:'试衣间', phonetic:'/ˈfɪtɪŋ ruːm/', example:'Where is the fitting room?', exampleCn:'试衣间在哪里？', category:'购物消费', usage:'life' },
{ word:'cash register', meaning:'收银台', phonetic:'/kæʃ ˈredʒɪstə(r)/', example:'Please pay at the cash register.', exampleCn:'请在收银台付款。', category:'购物消费', usage:'life' },
{ word:'refund', meaning:'退款', phonetic:'/ˈriːfʌnd/', example:'I would like a refund.', exampleCn:'我想退款。', category:'购物消费', usage:'life' },
{ word:'warranty', meaning:'保修', phonetic:'/ˈwɒrənti/', example:'Does this product come with a warranty?', exampleCn:'这个产品有保修吗？', category:'购物消费', usage:'life' },
{ word:'price tag', meaning:'价格标签', phonetic:'/praɪs tæɡ/', example:'Check the price tag before buying.', exampleCn:'购买前查看价格标签。', category:'购物消费', usage:'life' },
{ word:'credit card', meaning:'信用卡', phonetic:'/ˈkredɪt kɑːd/', example:'Can I pay by credit card?', exampleCn:'我可以用信用卡付款吗？', category:'购物消费', usage:'life' },
/* ---------- 紧急求助 ---------- */
{ word:'police station', meaning:'警察局', phonetic:'/pəˈliːs ˈsteɪʃn/', example:'Where is the nearest police station?', exampleCn:'最近的警察局在哪里？', category:'紧急求助', usage:'life' },
{ word:'embassy', meaning:'大使馆', phonetic:'/ˈembəsi/', example:'I need to contact my embassy.', exampleCn:'我需要联系我的大使馆。', category:'紧急求助', usage:'life' },
{ word:'consulate', meaning:'领事馆', phonetic:'/ˈkɒnsjələt/', example:'The consulate can help with passport issues.', exampleCn:'领事馆可以帮助处理护照问题。', category:'紧急求助', usage:'life' },
{ word:'pharmacy', meaning:'药店', phonetic:'/ˈfɑːməsi/', example:'Is there a pharmacy nearby?', exampleCn:'附近有药店吗？', category:'紧急求助', usage:'life' },
{ word:'emergency', meaning:'紧急情况', phonetic:'/ɪˈmɜːdʒənsi/', example:'This is an emergency.', exampleCn:'这是紧急情况。', category:'紧急求助', usage:'life' },
{ word:'fire extinguisher', meaning:'灭火器', phonetic:'/ˈfaɪə ɪkˈstɪŋɡwɪʃə(r)/', example:'Where is the fire extinguisher?', exampleCn:'灭火器在哪里？', category:'紧急求助', usage:'life' },
{ word:'prescription', meaning:'处方', phonetic:'/prɪˈskrɪpʃn/', example:'I need to fill a prescription.', exampleCn:'我需要按处方拿药。', category:'紧急求助', usage:'life' },
/* ---------- 日常交际 ---------- */
{ word:'appointment', meaning:'预约 / 约会', phonetic:'/əˈpɔɪntmənt/', example:'I have an appointment at 10:00 AM.', exampleCn:'我约了早上十点的预约。', category:'日常交际', usage:'life' },
{ word:'available', meaning:'有空的 / 可用的', phonetic:'/əˈveɪləbl/', example:'Are you available tomorrow?', exampleCn:'您明天有空吗？', category:'日常交际', usage:'life' },
{ word:'convenient', meaning:'方便的', phonetic:'/kənˈviːniənt/', example:'Is it convenient for you?', exampleCn:'您方便吗？', category:'日常交际', usage:'life' },
{ word:'postpone', meaning:'推迟', phonetic:'/pəˈspəʊn/', example:'Can we postpone the meeting?', exampleCn:'我们可以推迟会议吗？', category:'日常交际', usage:'life' },
{ word:'confirm', meaning:'确认', phonetic:'/kənˈfɜːm/', example:'Please confirm your reservation.', exampleCn:'请确认您的预订。', category:'日常交际', usage:'life' },
{ word:'recommend', meaning:'推荐', phonetic:'/ˌrekəˈmend/', example:'Can you recommend a good restaurant?', exampleCn:'您能推荐一家好餐厅吗？', category:'日常交际', usage:'life' },
{ word:'complaint', meaning:'投诉', phonetic:'/kəmˈpleɪnt/', example:'I would like to make a complaint.', exampleCn:'我要投诉。', category:'日常交际', usage:'life' },
{ word:'apology', meaning:'道歉', phonetic:'/əˈpɒlədʒi/', example:'Please accept my apology.', exampleCn:'请接受我的道歉。', category:'日常交际', usage:'life' },
{ word:'appreciate', meaning:'感激 / 感谢', phonetic:'/əˈpriːʃieɪt/', example:'I really appreciate your help.', exampleCn:'我非常感激您的帮助。', category:'日常交际', usage:'life' },
{ word:'excuse me', meaning:'打扰一下 / 不好意思', phonetic:'/ɪkˈskjuːz mi/', example:'Excuse me, could you help me?', exampleCn:'打扰一下，您能帮我吗？', category:'日常交际', usage:'life' },
{ word:'pleased to meet you', meaning:'很高兴见到你', phonetic:'/pliːzd tuː miːt juː/', example:'Pleased to meet you.', exampleCn:'很高兴见到您。', category:'日常交际', usage:'life' },
/* ---------- 特殊旅客服务 ---------- */
{ word:'wheelchair passenger', meaning:'轮椅旅客', phonetic:'/ˈwiːltʃeə(r) ˈpæsɪndʒə(r)/', example:'Please assist the wheelchair passenger to their seat.', exampleCn:'请协助轮椅旅客到达座位。', category:'特殊旅客服务', usage:'face' },
{ word:'unaccompanied minor', meaning:'无陪伴儿童', phonetic:'/ˌʌnəˈkʌmpənid ˈmaɪnə(r)/', example:'The crew is responsible for the unaccompanied minor.', exampleCn:'机组负责照看无陪伴儿童。', category:'特殊旅客服务', usage:'write' },
{ word:'special assistance', meaning:'特殊协助', phonetic:'/ˈspeʃl əˈsɪstəns/', example:'This passenger requires special assistance.', exampleCn:'该旅客需要特殊协助。', category:'特殊旅客服务', usage:'face' },
{ word:'visually impaired', meaning:'视力障碍的', phonetic:'/ˈvɪʒuəli ɪmˈpeəd/', example:'Guide the visually impaired passenger carefully.', exampleCn:'请小心引导视力障碍旅客。', category:'特殊旅客服务', usage:'face' },
{ word:'service animal', meaning:'服务犬', phonetic:'/ˈsɜːvɪs ˈænɪml/', example:'A service animal is permitted in the cabin.', exampleCn:'服务犬允许进入客舱。', category:'特殊旅客服务', usage:'face' },
{ word:'expectant mother', meaning:'孕妇', phonetic:'/ɪkˈspektənt ˈmʌðə(r)/', example:'Please offer priority seating to the expectant mother.', exampleCn:'请为孕妇提供优先座位。', category:'特殊旅客服务', usage:'face' },
{ word:'medical certificate', meaning:'医疗证明', phonetic:'/ˈmedɪkl səˈtɪfɪkət/', example:'A medical certificate is required for this passenger to fly.', exampleCn:'该旅客需要医疗证明方可登机。', category:'特殊旅客服务', usage:'write' },
/* ---------- 机组资源管理 ---------- */
{ word:'crew briefing', meaning:'机组简报', phonetic:'/kruː ˈbriːfɪŋ/', example:'Attend the crew briefing before boarding.', exampleCn:'登机前请参加机组简报。', category:'机组资源管理', usage:'write' },
{ word:'situational awareness', meaning:'情境意识', phonetic:'/ˌsɪtʃuˈeɪʃənl əˈweənəs/', example:'Maintain situational awareness throughout the flight.', exampleCn:'全程保持情境意识。', category:'机组资源管理', usage:'write' },
{ word:'cross-check', meaning:'交叉检查', phonetic:'/krɒs tʃek/', example:'Cross-check all cabin doors before departure.', exampleCn:'起飞前交叉检查所有舱门。', category:'机组资源管理', usage:'write' },
{ word:'debrief', meaning:'事后总结', phonetic:'/ˌdiːˈbriːf/', example:'The crew will debrief after landing.', exampleCn:'机组将在落地后进行事后总结。', category:'机组资源管理', usage:'write' },
{ word:'delegate task', meaning:'分派任务', phonetic:'/ˈdelɪɡeɪt tɑːsk/', example:'Delegate tasks clearly during an emergency.', exampleCn:'紧急情况下请明确分派任务。', category:'机组资源管理', usage:'write' },
{ word:'shift handover', meaning:'交接班', phonetic:'/ʃɪft ˈhændəʊvə(r)/', example:'Complete the shift handover report before leaving.', exampleCn:'离岗前完成交接班报告。', category:'机组资源管理', usage:'write' },
/* ---------- 证件类型扩展 ---------- */
{ word:'green card', meaning:'绿卡', phonetic:'/ɡriːn kɑːd/', example:'He presented a green card as identification.', exampleCn:'他出示了绿卡作为身份证明。', category:'证件类型扩展', usage:'write' },
{ word:'residence permit', meaning:'居留许可', phonetic:'/ˈrezɪdəns ˈpɜːmɪt/', example:'Please show your residence permit.', exampleCn:'请出示您的居留许可。', category:'证件类型扩展', usage:'face' },
{ word:'travel document', meaning:'旅行证件', phonetic:'/ˈtrævl ˈdɒkjumənt/', example:'This travel document has expired.', exampleCn:'这份旅行证件已过期。', category:'证件类型扩展', usage:'face' },
{ word:'birth certificate', meaning:'出生证明', phonetic:'/bɜːθ səˈtɪfɪkət/', example:'A birth certificate is required for the infant.', exampleCn:'婴儿需要出生证明。', category:'证件类型扩展', usage:'write' },
{ word:'crew manifest', meaning:'机组名单', phonetic:'/kruː ˈmænɪfest/', example:'Check the name against the crew manifest.', exampleCn:'核对姓名与机组名单。', category:'证件类型扩展', usage:'write' },
/* ---------- 复飞与备降 ---------- */
{ word:'go-around', meaning:'复飞', phonetic:'/ɡəʊ əˈraʊnd/', example:'The pilot initiated a go-around due to poor visibility.', exampleCn:'由于能见度差，飞行员执行了复飞。', category:'复飞与备降', usage:'radio' },
{ word:'alternate airport', meaning:'备降机场', phonetic:'/ˈɔːltəneɪt ˈeəpɔːt/', example:'We are diverting to the alternate airport.', exampleCn:'我们正在备降至备降机场。', category:'复飞与备降', usage:'radio' },
{ word:'fuel shortage', meaning:'燃油不足', phonetic:'/ˈfjuːəl ˈʃɔːtɪdʒ/', example:'A fuel shortage forced an early landing.', exampleCn:'燃油不足迫使提前降落。', category:'复飞与备降', usage:'write' },
{ word:'holding pattern', meaning:'等待航线', phonetic:'/ˈhəʊldɪŋ ˈpætən/', example:'The aircraft entered a holding pattern above the airport.', exampleCn:'飞机在机场上空进入了等待航线。', category:'复飞与备降', usage:'radio' },
{ word:'runway incursion', meaning:'跑道侵入', phonetic:'/ˈrʌnweɪ ɪnˈkɜːʒn/', example:'A runway incursion delayed the takeoff.', exampleCn:'一起跑道侵入事件延误了起飞。', category:'复飞与备降', usage:'write' },
/* ---------- 涉外文书笔录 ---------- */
{ word:'witness statement', meaning:'证人证言', phonetic:'/ˈwɪtnəs ˈsteɪtmənt/', example:'Please provide a witness statement.', exampleCn:'请提供一份证人证言。', category:'涉外文书笔录', usage:'write' },
{ word:'timeline of events', meaning:'事件时间线', phonetic:'/ˈtaɪmlaɪn əv ɪˈvents/', example:'Record a clear timeline of events.', exampleCn:'请记录清晰的事件时间线。', category:'涉外文书笔录', usage:'write' },
{ word:'incident summary', meaning:'事件摘要', phonetic:'/ˈɪnsɪdənt ˈsʌməri/', example:'Attach an incident summary to the report.', exampleCn:'请在报告中附上事件摘要。', category:'涉外文书笔录', usage:'write' },
{ word:'photographic evidence', meaning:'影像证据', phonetic:'/ˌfəʊtəˈɡræfɪk ˈevɪdəns/', example:'Photographic evidence was attached to the case file.', exampleCn:'案件档案中附有影像证据。', category:'涉外文书笔录', usage:'write' },
{ word:'case file', meaning:'案卷', phonetic:'/keɪs faɪl/', example:'The case file was handed to the police.', exampleCn:'案卷已移交给警方。', category:'涉外文书笔录', usage:'write' },
{ word:'follow-up investigation', meaning:'后续调查', phonetic:'/ˈfɒləʊ ʌp ɪnˌvestɪˈɡeɪʃn/', example:'A follow-up investigation will be conducted on the ground.', exampleCn:'落地后将进行后续调查。', category:'涉外文书笔录', usage:'write' },
/* ---------- 常见突发情境 ---------- */
{ word:'stowaway', meaning:'偷渡者', phonetic:'/ˈstəʊəweɪ/', example:'A stowaway was discovered in the cargo hold.', exampleCn:'在货舱中发现了一名偷渡者。', category:'常见突发情境', usage:'write' },
{ word:'lost child', meaning:'走失儿童', phonetic:'/lɒst tʃaɪld/', example:'Report any lost child to the crew immediately.', exampleCn:'如发现走失儿童请立即报告机组。', category:'常见突发情境', usage:'radio' },
{ word:'theft onboard', meaning:'机上盗窃', phonetic:'/θeft ɒnˈbɔːd/', example:'A theft onboard was reported by a passenger.', exampleCn:'一名旅客报告了机上盗窃事件。', category:'常见突发情境', usage:'write' },
{ word:'domestic dispute', meaning:'家庭纠纷', phonetic:'/dəˈmestɪk dɪˈspjuːt/', example:'Crew intervened in a domestic dispute between passengers.', exampleCn:'机组介入了旅客间的家庭纠纷。', category:'常见突发情境', usage:'write' },
{ word:'harassment', meaning:'骚扰', phonetic:'/həˈræsmənt/', example:'A passenger reported harassment by another traveler.', exampleCn:'一名旅客报告了被另一名旅客骚扰的情况。', category:'常见突发情境', usage:'write' },
{ word:'photography restriction', meaning:'拍照限制', phonetic:'/fəˈtɒɡrəfi rɪˈstrɪkʃn/', example:'Photography restriction applies near the cockpit.', exampleCn:'驾驶舱附近适用拍照限制。', category:'常见突发情境', usage:'face' },
{ word:'electronic device interference', meaning:'电子设备干扰', phonetic:'/ˌɪlekˈtrɒnɪk dɪˈvaɪs ˌɪntəˈfɪərəns/', example:'Electronic device interference was suspected during approach.', exampleCn:'进近阶段怀疑存在电子设备干扰。', category:'常见突发情境', usage:'write' },
/* ---------- 天气预警补充 ---------- */
{ word:'severe weather warning', meaning:'恶劣天气预警', phonetic:'/sɪˈvɪə(r) ˈweðə(r) ˈwɔːnɪŋ/', example:'A severe weather warning was issued for the route.', exampleCn:'该航路已发布恶劣天气预警。', category:'天气预警补充', usage:'write' },
{ word:'icing conditions', meaning:'结冰状况', phonetic:'/ˈaɪsɪŋ kənˈdɪʃnz/', example:'Icing conditions delayed the departure.', exampleCn:'结冰状况延误了起飞。', category:'天气预警补充', usage:'write' },
{ word:'visibility', meaning:'能见度', phonetic:'/ˌvɪzəˈbɪləti/', example:'Visibility dropped sharply due to fog.', exampleCn:'由于大雾，能见度急剧下降。', category:'天气预警补充', usage:'write' },
{ word:'crosswind', meaning:'侧风', phonetic:'/ˈkrɒswɪnd/', example:'A strong crosswind affected the landing.', exampleCn:'强侧风影响了着陆。', category:'天气预警补充', usage:'write' },
{ word:'wind shear', meaning:'风切变', phonetic:'/wɪnd ʃɪə(r)/', example:'Wind shear was reported near the runway.', exampleCn:'跑道附近报告了风切变。', category:'天气预警补充', usage:'radio' },
/* ---------- 数字时间补充 ---------- */
{ word:'ETA', meaning:'预计到达时间', phonetic:'/ˌiː tiː ˈeɪ/', example:'Our ETA is 14:30 local time.', exampleCn:'我们预计当地时间14:30到达。', category:'数字时间补充', usage:'radio' },
{ word:'local time', meaning:'当地时间', phonetic:'/ˈləʊkl taɪm/', example:'Please set your watch to local time.', exampleCn:'请将手表调整为当地时间。', category:'数字时间补充', usage:'life' },
{ word:'time zone', meaning:'时区', phonetic:'/taɪm zəʊn/', example:'The destination is in a different time zone.', exampleCn:'目的地处于不同的时区。', category:'数字时间补充', usage:'life' },
{ word:'countdown', meaning:'倒计时', phonetic:'/ˈkaʊntdaʊn/', example:'The countdown to landing has begun.', exampleCn:'着陆倒计时已经开始。', category:'数字时间补充', usage:'radio' },
/* ---------- 客舱服务礼仪 ---------- */
{ word:'greet passengers', meaning:'迎接旅客', phonetic:'/ɡriːt ˈpæsɪndʒəz/', example:'Greet passengers with a smile at the door.', exampleCn:'在舱门处微笑迎接旅客。', category:'客舱服务礼仪', usage:'face' },
{ word:'professional tone', meaning:'专业语气', phonetic:'/prəˈfeʃənl təʊn/', example:'Always speak in a professional tone.', exampleCn:'始终使用专业语气讲话。', category:'客舱服务礼仪', usage:'face' },
{ word:'active listening', meaning:'积极倾听', phonetic:'/ˈæktɪv ˈlɪsnɪŋ/', example:'Active listening helps resolve conflicts.', exampleCn:'积极倾听有助于化解冲突。', category:'客舱服务礼仪', usage:'face' },
{ word:'body language', meaning:'肢体语言', phonetic:'/ˈbɒdi ˈlæŋɡwɪdʒ/', example:'Watch the passenger’s body language closely.', exampleCn:'密切观察旅客的肢体语言。', category:'客舱服务礼仪', usage:'write' },
{ word:'eye contact', meaning:'眼神交流', phonetic:'/aɪ ˈkɒntækt/', example:'Maintain eye contact while giving instructions.', exampleCn:'给出指示时请保持眼神交流。', category:'客舱服务礼仪', usage:'face' },
/* ---------- 行业常用缩略语 ---------- */
{ word:'ICAO', meaning:'国际民航组织', phonetic:'/ˌaɪ siː eɪ ˈəʊ/', example:'ICAO sets global aviation security standards.', exampleCn:'国际民航组织制定全球航空安保标准。', category:'行业常用缩略语', usage:'write' },
{ word:'IATA', meaning:'国际航空运输协会', phonetic:'/aɪˈɑːtə/', example:'IATA regulations govern dangerous goods transport.', exampleCn:'国际航空运输协会的规定管理危险品运输。', category:'行业常用缩略语', usage:'write' },
{ word:'CAAC', meaning:'中国民用航空局', phonetic:'/siː eɪ eɪ ˈsiː/', example:'CAAC issued a new security directive.', exampleCn:'中国民用航空局发布了新的安保指令。', category:'行业常用缩略语', usage:'write' },
{ word:'TSA', meaning:'美国运输安全管理局', phonetic:'/tiː es ˈeɪ/', example:'TSA officers conduct passenger screening in the US.', exampleCn:'美国运输安全管理局在美国负责旅客安检。', category:'行业常用缩略语', usage:'write' },
{ word:'ATC', meaning:'空中交通管制', phonetic:'/eɪ tiː ˈsiː/', example:'ATC cleared the aircraft for landing.', exampleCn:'空中交通管制批准飞机降落。', category:'行业常用缩略语', usage:'radio' },
{ word:'ETD', meaning:'预计起飞时间', phonetic:'/iː tiː ˈdiː/', example:'The ETD has been pushed back by 30 minutes.', exampleCn:'预计起飞时间推迟了30分钟。', category:'行业常用缩略语', usage:'write' },
{ word:'PIC', meaning:'责任机长', phonetic:'/piː aɪ ˈsiː/', example:'The PIC makes the final decision on all safety matters.', exampleCn:'责任机长对所有安全事项做最终决定。', category:'行业常用缩略语', usage:'write' },
{ word:'SOP', meaning:'标准操作程序', phonetic:'/es əʊ ˈpiː/', example:'Always follow the SOP during an incident.', exampleCn:'事件发生时请始终遵循标准操作程序。', category:'行业常用缩略语', usage:'write' },
/* ---------- 登机口特殊处置 ---------- */
{ word:'gate agent', meaning:'登机口地勤', phonetic:'/ɡeɪt ˈeɪdʒənt/', example:'The gate agent denied boarding to the passenger.', exampleCn:'登机口地勤拒绝了该旅客登机。', category:'登机口特殊处置', usage:'write' },
{ word:'denied boarding', meaning:'拒绝登机', phonetic:'/dɪˈnaɪd ˈbɔːdɪŋ/', example:'He was denied boarding due to invalid documents.', exampleCn:'由于证件无效，他被拒绝登机。', category:'登机口特殊处置', usage:'write' },
{ word:'overbooking', meaning:'超额订座', phonetic:'/ˌəʊvəˈbʊkɪŋ/', example:'The flight was affected by overbooking.', exampleCn:'该航班受到超额订座的影响。', category:'登机口特殊处置', usage:'write' },
{ word:'standby passenger', meaning:'候补旅客', phonetic:'/ˈstændbaɪ ˈpæsɪndʒə(r)/', example:'Standby passengers will board after confirmed passengers.', exampleCn:'候补旅客将在确认旅客之后登机。', category:'登机口特殊处置', usage:'face' },
{ word:'priority boarding', meaning:'优先登机', phonetic:'/praɪˈɒrəti ˈbɔːdɪŋ/', example:'Priority boarding is offered to families with children.', exampleCn:'带儿童的家庭可优先登机。', category:'登机口特殊处置', usage:'face' },
{ word:'gate closed', meaning:'登机口已关闭', phonetic:'/ɡeɪt kləʊzd/', example:'I am sorry, the gate is closed.', exampleCn:'很抱歉，登机口已关闭。', category:'登机口特殊处置', usage:'face' },
/* ---------- 货运与危险品运输 ---------- */
{ word:'cargo hold', meaning:'货舱', phonetic:'/ˈkɑːɡəʊ həʊld/', example:'The item was found in the cargo hold.', exampleCn:'该物品是在货舱内发现的。', category:'货运与危险品运输', usage:'write' },
{ word:'hazmat label', meaning:'危险品标签', phonetic:'/ˈhæzmæt ˈleɪbl/', example:'Check for a hazmat label on the package.', exampleCn:'检查包裹上是否有危险品标签。', category:'货运与危险品运输', usage:'write' },
{ word:'weight restriction', meaning:'重量限制', phonetic:'/weɪt rɪˈstrɪkʃn/', example:'The cargo exceeded the weight restriction.', exampleCn:'该货物超出了重量限制。', category:'货运与危险品运输', usage:'write' },
{ word:'freight manifest', meaning:'货运舱单', phonetic:'/freɪt ˈmænɪfest/', example:'Compare the cargo with the freight manifest.', exampleCn:'将货物与货运舱单进行比对。', category:'货运与危险品运输', usage:'write' },
{ word:'loading supervisor', meaning:'装卸监督员', phonetic:'/ˈləʊdɪŋ ˈsuːpəvaɪzə(r)/', example:'The loading supervisor confirmed the cargo was secure.', exampleCn:'装卸监督员确认了货物已固定妥当。', category:'货运与危险品运输', usage:'write' },
/* ---------- 卫生与消毒 ---------- */
{ word:'sanitize', meaning:'消毒', phonetic:'/ˈsænɪtaɪz/', example:'Please sanitize your hands before boarding.', exampleCn:'登机前请对双手进行消毒。', category:'卫生与消毒', usage:'face' },
{ word:'contamination', meaning:'污染', phonetic:'/kənˌtæmɪˈneɪʃn/', example:'Report any suspected contamination immediately.', exampleCn:'如怀疑污染请立即报告。', category:'卫生与消毒', usage:'write' },
{ word:'isolation seat', meaning:'隔离座位', phonetic:'/ˌaɪsəˈleɪʃn siːt/', example:'Move the ill passenger to an isolation seat.', exampleCn:'将患病旅客移至隔离座位。', category:'卫生与消毒', usage:'write' },
{ word:'protective gloves', meaning:'防护手套', phonetic:'/prəˈtektɪv ɡʌvz/', example:'Wear protective gloves during the search.', exampleCn:'检查时请佩戴防护手套。', category:'卫生与消毒', usage:'face' },
{ word:'face mask', meaning:'口罩', phonetic:'/feɪs mɑːsk/', example:'A face mask is required in this area.', exampleCn:'此区域要求佩戴口罩。', category:'卫生与消毒', usage:'face' },
/* ---------- 情绪与沟通技巧 ---------- */
{ word:'reassure', meaning:'安抚', phonetic:'/ˌriːəˈʃʊə(r)/', example:'Reassure the passenger that help is on the way.', exampleCn:'安抚旅客告知帮助正在赶来。', category:'情绪与沟通技巧', usage:'face' },
{ word:'empathize', meaning:'共情 / 理解感受', phonetic:'/ˈempəθaɪz/', example:'Try to empathize before setting boundaries.', exampleCn:'在设定界限前请先尝试共情。', category:'情绪与沟通技巧', usage:'face' },
{ word:'set boundaries', meaning:'设立界限', phonetic:'/set ˈbaʊndriz/', example:'Set boundaries clearly and calmly.', exampleCn:'请清晰而冷静地设立界限。', category:'情绪与沟通技巧', usage:'face' },
{ word:'assertive tone', meaning:'坚定的语气', phonetic:'/əˈsɜːtɪv təʊn/', example:'Use an assertive tone without raising your voice.', exampleCn:'使用坚定的语气但不要提高音量。', category:'情绪与沟通技巧', usage:'face' },
{ word:'give a choice', meaning:'给予选择', phonetic:'/ɡɪv ə tʃɔɪs/', example:'Give the passenger a choice when possible.', exampleCn:'尽可能给旅客提供选择。', category:'情绪与沟通技巧', usage:'face' },
{ word:'active de-escalation', meaning:'主动缓和技巧', phonetic:'/ˈæktɪv diː ˌeskəˈleɪʃn/', example:'Active de-escalation reduces the risk of conflict.', exampleCn:'主动缓和技巧可降低冲突风险。', category:'情绪与沟通技巧', usage:'write' },
/* ---------- 客舱异物与设备故障 ---------- */
{ word:'foreign object', meaning:'异物', phonetic:'/ˈfɒrən ˈɒbdʒɪkt/', example:'A foreign object was found under the seat.', exampleCn:'座位下方发现了一件异物。', category:'客舱异物与设备故障', usage:'write' },
{ word:'malfunction', meaning:'故障', phonetic:'/ˌmælˈfʌŋkʃn/', example:'Report any equipment malfunction right away.', exampleCn:'如设备出现故障请立即报告。', category:'客舱异物与设备故障', usage:'radio' },
{ word:'battery overheating', meaning:'电池过热', phonetic:'/ˈbætəri ˌəʊvəˈhiːtɪŋ/', example:'Battery overheating was detected in a passenger device.', exampleCn:'检测到某旅客设备电池过热。', category:'客舱异物与设备故障', usage:'radio' },
{ word:'smoke detector', meaning:'烟雾探测器', phonetic:'/sməʊk dɪˈtektə(r)/', example:'The smoke detector was triggered in the lavatory.', exampleCn:'洗手间内的烟雾探测器被触发。', category:'客舱异物与设备故障', usage:'radio' },
{ word:'strange odor', meaning:'异常气味', phonetic:'/streɪndʒ ˈəʊdə(r)/', example:'A strange odor was reported near row 10.', exampleCn:'10排附近报告了异常气味。', category:'客舱异物与设备故障', usage:'radio' },
/* ---------- 团队协作口令 ---------- */
{ word:'back me up', meaning:'支援我', phonetic:'/bæk miː ʌp/', example:'Back me up at row 18, please.', exampleCn:'请到18排支援我。', category:'团队协作口令', usage:'radio' },
{ word:'take position', meaning:'就位', phonetic:'/teɪk pəˈzɪʃn/', example:'Take position near the forward door.', exampleCn:'在前舱门附近就位。', category:'团队协作口令', usage:'radio' },
{ word:'all clear', meaning:'情况解除', phonetic:'/ɔːl klɪə(r)/', example:'All clear, situation resolved.', exampleCn:'情况解除，事件已处理。', category:'团队协作口令', usage:'radio' },
{ word:'hold your position', meaning:'保持原位', phonetic:'/həʊld jɔː pəˈzɪʃn/', example:'Hold your position until I arrive.', exampleCn:'在我到达前请保持原位。', category:'团队协作口令', usage:'radio' },
{ word:'switch channel', meaning:'切换频道', phonetic:'/swɪtʃ ˈtʃænl/', example:'Switch channel to contact the cockpit directly.', exampleCn:'切换频道以直接联系驾驶舱。', category:'团队协作口令', usage:'radio' },
/* ---------- 结束用语 ---------- */
{ word:'case closed', meaning:'事件了结', phonetic:'/keɪs kləʊzd/', example:'The case is now closed after the police report.', exampleCn:'警方报告完成后该事件已了结。', category:'结束用语', usage:'write' },
{ word:'resolved without incident', meaning:'平稳处置完毕', phonetic:'/rɪˈzɒlvd wɪˈðaʊt ˈɪnsɪdənt/', example:'The situation was resolved without incident.', exampleCn:'该情况已平稳处置完毕。', category:'结束用语', usage:'write' },
{ word:'debrief complete', meaning:'总结完毕', phonetic:'/ˌdiːˈbriːf kəmˈpliːt/', example:'Debrief complete, all crew may stand down.', exampleCn:'总结完毕，全体机组可解除待命。', category:'结束用语', usage:'radio' },
{ word:'thank you for your service', meaning:'感谢您的辛勤付出', phonetic:'/θæŋk juː fɔː jɔː ˈsɜːvɪs/', example:'Thank you for your service today.', exampleCn:'感谢您今天的辛勤付出。', category:'结束用语', usage:'face' },
{ word:'well done, team', meaning:'团队干得漂亮', phonetic:'/wel dʌn tiːm/', example:'Well done, team. Great handling of that situation.', exampleCn:'团队干得漂亮，这次处置很出色。', category:'结束用语', usage:'face' },
{ word:'shift supervisor', meaning:'带班组长', phonetic:'/ʃɪft ˈsuːpəvaɪzə(r)/', example:'Inform the shift supervisor of any irregularity.', exampleCn:'如有异常请通知带班组长。', category:'岗位', usage:'write' },
{ word:'duty roster', meaning:'排班表', phonetic:'/ˈdjuːti ˈrɒstə(r)/', example:'Check the duty roster before your shift.', exampleCn:'执勤前请查看排班表。', category:'岗位', usage:'write' },
{ word:'briefing room', meaning:'讲评室', phonetic:'/ˈbriːfɪŋ ruːm/', example:'All crew must attend the briefing room session.', exampleCn:'全体机组必须参加讲评室会议。', category:'岗位', usage:'write' },
{ word:'flight duration', meaning:'飞行时长', phonetic:'/flaɪt djʊˈreɪʃn/', example:'The flight duration is approximately eleven hours.', exampleCn:'飞行时长约为十一小时。', category:'航班', usage:'face' },
{ word:'layover', meaning:'中转停留', phonetic:'/ˈleɪəʊvə(r)/', example:'We have a six-hour layover in Doha.', exampleCn:'我们在多哈有六小时的中转停留。', category:'航班', usage:'life' }
];
